#config_version=5

mode:
  start_events: start_mode_Song_8
  stop_events: ball_ended, mode_Song_Carousel_10_starting
  priority: 200

sound_player:
  mode_Song_8_started:
    Cult_track:
      action: play
      loops: -1
  ball_ending:
    Cult_track:
      action: stop

slides:
  pick_Song8_slide: #Cult Leader
    - type: video
      video: cult_track
      control_events:
        - event: bd_right_saucer_ball_eject_success
          action: stop

slide_player:
  mode_Song_8_started: 
    pick_Song8_slide:
      target: dmd