#config_version=5

mode:
  start_events: start_mode_Song_1
  stop_events: ball_ended, mode_Song_Carousel_4_starting
  priority: 200

sound_player:
  mode_Song_1_started:
    Voices_track:
      action: play
      loops: -1
  ball_ending:
    Voices_track:
      action: stop
  mode_Song_1_ending:
    Voices_track:
      action: stop

show_player:
  mode_Song_1_started: 
    footsteps_track:
      loops: 0
      speed: 1