#config_version=5

mode:
  start_events: drop_target_shot_hit
  stop_events: multiball_collide_mb_ended
  priority: 500

multiball_locks:
  collide_lock:
    debug: true
    balls_to_lock: 5
    lock_devices: bd_ramp_load
    reset_all_counts_events:  multiball_collide_mb_ended
    #enable_events: ball_starting, multiball_collide_mb_ended
    #locked_ball_counting_strategy: physical_only

multiballs:
  collide_mb:
    ball_count: device.multiball_locks.collide_lock.locked_balls
    ball_count_type: add
    ball_locks: bd_ramp_load
    start_events: multiball_lock_collide_lock_full, ev_start_multiball

event_player:
  eject_chamber_shot_hit:
    - ev_start_multiball

variable_player:
  balls_in_play{balls==2}:
    pf_MBall_multiplier: 
      int: 2
      action: set
  balls_in_play{balls==3}:
    pf_MBall_multiplier: 
      int: 3
      action: set
  balls_in_play{balls==4}:
    pf_MBall_multiplier: 
      int: 4
      action: set
  balls_in_play{balls==5}:
    pf_Mball_multiplier: 
      int: 5
      action: set
  multiball_collide_mb_ended:
    pf_Mball_multiplier:
      int: 1
      action: set

timers:
    mb_shoot_again_timer:
        start_value: 10
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: multiball_collide_mb_started

sequences:
  lb_Level_2:
    events:
      - timer_drop_target_01_started 
      - multiball_lock_collide_lock_locked_ball{total_balls_locked==1}
    events_when_complete: 
      - Level_2_Flash
  lb_Level_3:
    events:
      - timer_drop_target_01_started 
      - multiball_lock_collide_lock_locked_ball{total_balls_locked==2}
    events_when_complete: 
      - Level_3_Flash
  lb_Level_4:
    events:
      - timer_drop_target_01_started 
      - multiball_lock_collide_lock_locked_ball{total_balls_locked==3}
    events_when_complete: 
      - Level_4_Flash
  lb_Level_5:
    events:
      - timer_drop_target_01_started 
      - multiball_lock_collide_lock_locked_ball{total_balls_locked==4}
    events_when_complete: 
      - Level_5_Flash
  lb_Level_2_song:
    events:
      - balls_in_play{balls==2}
      - multiball_collide_mb_started
    disable_events: multiball_lock_collide_lock_locked_ball{total_balls_locked>2}
    events_when_complete: 
      - Level_2_Play
  lb_Level_3_song:
    events:
      - balls_in_play{balls==3}
      - multiball_collide_mb_started
    disable_events: multiball_lock_collide_lock_locked_ball{total_balls_locked>3}
    events_when_complete: 
      - Level_3_Play
  lb_Level_4_song:
    events:
      - balls_in_play{balls==4}
      - multiball_collide_mb_started
    disable_events: multiball_lock_collide_lock_locked_ball{total_balls_locked>4}
    events_when_complete: 
      - Level_4_Play
  lb_Level_5_song:
    events:
      - balls_in_play{balls==5}
      - multiball_collide_mb_started
    disable_events: multiball_lock_collide_lock_locked_ball{total_balls_locked>5}
    events_when_complete: 
      - Level_5_Play

show_player:
  timer_mb_shoot_again_timer_started:
    Rock_Again_On:
      show_tokens:
        lights: Rock_Again
  timer_mb_shoot_again_timer_stopped:
    Rock_Again_Off:
      show_tokens:
        lights: Rock_Again
  timer_drop_target_01_started:
    flash:
      loops: -1
      speed: 2
      show_tokens:
        lights: Level_1
  multiball_lock_collide_lock_locked_ball{total_balls_locked==1}:
    Level_1_On:
      show_tokens:
        lights: Level_1
  Level_2_Flash:
    flash:
      loops: -1
      speed: 2
      show_tokens:
        lights: Level_2
  multiball_lock_collide_lock_locked_ball{total_balls_locked==2}:
    Level_2_On:
      show_tokens:
        lights: Level_2
  Level_3_Flash:
    flash:
      loops: -1
      speed: 2
      show_tokens:
        lights: Level_3
  multiball_lock_collide_lock_locked_ball{total_balls_locked==3}:
    Level_3_On:
      show_tokens:
        lights: Level_3
  Level_4_Flash:
    flash:
      loops: -1
      speed: 2
      show_tokens:
        lights: Level_4
  multiball_lock_collide_lock_locked_ball{total_balls_locked==4}:
    Level_4_On:
      show_tokens:
        lights: Level_4
  Level_5_Flash:
    flash:
      loops: -1
      speed: 2
      show_tokens:
        lights: Level_5
  multiball_lock_collide_lock_locked_ball{total_balls_locked==5}:
    Level_5_On:
      show_tokens:
        lights: Level_5
  multiball_collide_mb_started:
    Level_1_Off:
      show_tokens:
        lights: Level_1
    Level_2_Off:
      show_tokens:
        lights: Level_2
    Level_3_Off:
      show_tokens:
        lights: Level_3
    Level_4_Off:
     show_tokens:
        lights: Level_4
    Level_5_Off:
      show_tokens:
        lights: Level_5

  Level_2_Play:
    play_Tokyo:
      loops: 0
      speed: 1
  Level_3_Play:
    play_Bombshell:
      loops: 0
      speed: 1
  Level_4_Play:
    play_Hostage:
      loops: 0
      speed: 1
  Level_5_Play:
    play_Collide:
      loops: 0
      speed: 1

sound_player:
  Level_2_Play:
    Instrumental_track:
      action: stop
    Tokyo_track:
      action: play
      loops: -1
  Level_3_Play:
    Instrumental_track:
      action: stop
    Bombshell_track:
      action: play
      loops: -1
  Level_4_Play:
    Instrumental_track:
      action: stop
    Hostage_track:
      action: play
      loops: -1
  Level_5_Play:
    Instrumental_track:
      action: stop
    Worlds_track:
      action: play
      loops: -1