#config_version=5

mode:
  start_events: start_mode_Song_3
  stop_events: ball_ended, mode_Song_Carousel_4_starting
  priority: 200

sound_player:
  mode_Song_3_started:
    Showme_track:
      action: play
      loops: -1
  ball_ending:
    Showme_track:
      action: stop
  mode_Song_3_ending:
    Showme_track:
      action: stop

show_player:
  mode_Song_3_started: 
    showme_track:
      loops: 0
      speed: 1