#config_version=5

mode:
  start_events: start_mode_Song_3
  stop_events: ball_ended
  priority: 200

sound_player:
  mode_Setlist_started:
    Hostage_track:
      action: stop
    Invade_track:
      action: play
      loops: -1