#config_version=5

mode:
  start_events: Jukebox_Start{current_player.pf_setlist==7}  
  stop_events: ball_ended, mode_Song_Carousel_22_starting
  priority: 200

event_player:
  mode_Song_Carousel_19_started: play_random_song_7

random_event_player:
  play_random_song_7:
    force_different: true
    events:
      - Song_19
      - Song_20
      - Song_21

sound_player:
  mode_Song_Carousel_19_starting:
    Instrumental_track:
      action: stop
    Everything_track:
      action: stop
    Ultra_track:
      action: stop
    Revolution_track:
      action: stop
    cheering:
      action: play
      loops: 0  
  mode_Song_Carousel_19_ending:
    Love_track:
      action: stop
    Nobody_track:
      action: stop
    Walking_track:
      action: stop

  Song_19:
    Love_track:
      action: play
      loops: -1

  Song_20:
    Nobody_track:
      action: play
      loops: -1

  Song_21:
    Walking_track:
      action: play
      loops: -1

variable_player:
  mode_Song_Carousel_19_started:
    pf_setlist:
      int: 8
      action: set
    pf_Album_7_Ready:
      int: 0
      action: set

show_player:

  Song_19: 
    love_track:
      loops: 0
      speed: 1

  Song_20: 
    nobodys_track:
      loops: 0
      speed: 1

  Song_21: 
    walking_track:
      loops: 0
      speed: 1

  mode_Song_Carousel_19_started:
    guitar_award:
      speed: 10
      show_tokens:
        lights: Guitar_1K, Guitar_2K, Guitar_4K, Guitar_8K, Guitar_16K, Guitar_32K, Guitar_64K