#config_version=5

mode:
  start_events: balldevice_bd_left_saucer_ball_entered{current_player.pf_album==2}  
  stop_events: ball_ended, mode_Album_Award_03_starting
  priority: 200

event_player:
  mode_Album_Award_02_started: award_random_album_2

random_event_player:
  award_random_album_2:
    force_different: true
    events:
      - start_mode_Album_04
      - start_mode_Album_05
      - start_mode_Album_06

variable_player:
  mode_Album_Award_02_started:
    pf_album:
      int: 3
      action: set

  balldevice_bd_left_saucer_ball_entered:
    score: 2000 * current_player.pf_multiplier

  
#Tonight The Stars Revolt
#Backstage and Beyond the Infinite
#Anyone For Doomsday?