#config_version=5

mode:
  start_events: start_mode_Song_14
  stop_events: ball_ended, mode_Song_Carousel_16_starting
  priority: 200

sound_player:
  mode_Song_14_started:
    Villain_track:
      action: play
      loops: -1
  ball_ending:
    Villain_track:
      action: stop

show_player:
  mode_Song_14_started: 
    villain_track:
      loops: 0
      speed: 1