#config_version=5

mode:
  start_events: start_mode_Member_20
  stop_events: ball_ended, mode_Member_Award_Jackpot_starting
  priority: 200

show_player:
  mode_Member_20_started: 
    BSRS_Album:
      loops: 0
      speed: 1