#config_version=5

mode:
  start_events: start_mode_Song_10
  stop_events: mode_Song_Carousel_13_starting
  priority: 200

sound_player:
  mode_Song_10_started:
    Vampire_track:
      action: play
      loops: -1
  ball_ending:
    Vampire_track:
      action: stop

show_player:
  mode_Song_10_started: 
    vampire_track:
      loops: 0
      speed: 1