#config_version=5

mode:
  start_events: start_mode_Song_2
  stop_events: mode_Song_Carousel_4_starting
  priority: 200

sound_player:
  mode_Song_2_started:
    Invade_track:
      action: play
      loops: -1
  ball_ending:
    Invade_track:
      action: stop
  mode_Song_2_ending:
    Invade_track:
      action: stop


show_player:
  mode_Song_2_started: 
    invade_track:
      loops: 0
      speed: 1