#config_version=5

mode:
  start_events: start_mode_Song_10_Carousel
  stop_events: mode_Song_10_start, mode_Song_11_start, mode_Song_12_start
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 300

mode_settings:
  selectable_items: Song10, Song11, Song12, 
  select_item_events: sw_Both_Flippers
  next_item_events: sw_right_flipper_active
  previous_item_events: sw_left_flipper_active

queue_relay_player:
  balldevice_bd_right_saucer_eject_attempt:
    post: start_mode_Song_10_Carousel
    wait_for: mode_Song_10_start, mode_Song_11_start, mode_Song_12_start

slide_player:
  carousel_Song10_highlighted: select_Song10
  carousel_Song11_highlighted: select_Song11
  carousel_Song12_highlighted: select_Song12

slides:
  select_Song10: #Danger Is Go
    widgets:
      - type: image
        image: afd
    transition:
      type: move_in
      direction: right
  select_Song11: #V Is For Vampire
    widgets:
      - type: image
        image: sotoson
    transition:
      type: move_in
      direction: right
  select_Song12: #Destroy What You Enjoy
    widgets:
      - type: image
        image: dwye
    transition:
      type: move_in
      direction: right
 
event_player:
  select_Song10: mode_Song_10_start
  select_Song11: mode_Song_11_start
  select_Song12: mode_Song_12_start  