#config_version=5

mode:
  start_events: reset_ALBUM{current_player.pf_album==3}  
  stop_events: ball_ended, mode_Album_Award_04_starting
  priority: 200

event_player:
  mode_Album_Award_03_started: award_random_album_3

random_event_player:
  award_random_album_3:
    force_different: true
    events:
      - start_mode_Album_07
      - start_mode_Album_08
      - start_mode_Album_09

variable_player:
  mode_Album_Award_03_started:
    pf_album:
      int: 4
      action: set

  balldevice_bd_left_saucer_ball_entered:
    score: 30000 * current_player.pf_multiplier  * current_player.pf_MBall_multiplier

show_player:
  mode_Album_Award_03_started:
    Album_Off:
      show_tokens:
        lights: l_album_a, l_album_l, l_album_b, l_albumu, l_album_m
        
sound_player:
  award_random_album_3:
    new_album_collected:
      action: play
      loops: 0