#config_version=5

mode:
  start_events: start_mode_Song_4
  stop_events: ball_ended, mode_Song_Carousel_7_starting
  priority: 200

sound_player:
  mode_Song_4_started:
    Human_track:
      action: play
      loops: -1
  ball_ending:
    Human_track:
      action: stop

slides:
  pick_Song4_slide: #How To Be A Human
    - type: video
      video: human_track
      control_events:
        - event: bd_right_saucer_ball_eject_success
          action: stop
slide_player:
  mode_Song_4_started: 
    pick_Song4_slide:
      target: dmd