#config_version=5

mode:
  start_events: start_mode_Song_4
  stop_events: mode_Song_Carousel_7_starting
  priority: 200

sound_player:
  mode_Song_4_started:
    Human_track:
      action: play
      loops: -1
  ball_ending:
    Human_track:
      action: stop

show_player:
  mode_Song_4_started: 
    human_track:
      loops: 0
      speed: 1