#config_version=5

mode:
  start_events: ball_starting
  priority: 110

counters:
  lb_Skull_complete_count:
    count_events: Skull_lanes_complete
    events_when_hit: Skull_lanes_done
    starting_count: 1
    direction: up
    persist_state: false

shots:
  top_lane_L:
    switch: s_top_lane_L
    show_tokens:
      light: l_Skull_L
  top_lane_C:
    switch: s_top_lane_C
    show_tokens:
      light: l_Skull_C
  top_lane_R:
    switch: s_top_lane_R
    show_tokens:
      light: l_Skull_R

shot_groups:
  Skull_lanes:
    shots: top_lane_L, top_lane_C, top_lane_R
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active
    reset_events: 
      Skull_lanes_lit_complete: 1s

variable_player:
  mode_Skull_rollover_started:
    pf_multiplier:
      int: 1
      action: set

  Skull_lanes_done{count==2}:
    pf_multiplier:
      int: 2
      action: set

  Skull_lanes_done{count==3}:
    pf_multiplier:
      int: 3
      action: set

  Skull_lanes_done{count==4}:
    pf_multiplier:
      int: 4
      action: set

  Skull_lanes_done{count==5}:
     pf_multiplier:
      int: 5
      action: set

  Skull_lanes_done{count==6}:
    pf_multiplier:
      int: 10
      action: set

  Skull_lanes_complete:
    score: 1000 * current_player.pf_multiplier # * current_player.pf_MBall_multiplier|block
    pf_Skulls_ready:
      int: 1
      action: set

show_player:
  Skull_lanes_lit_complete:
    flash: 
      loops: 4
      speed: 4
      show_tokens:
        lights: Skull_lanes

  Skull_lanes_done{count==2}:
    Playfield_2x_on:
      show_tokens:
        lights: Playfield_2X

  Skull_lanes_done{count==3}:
    Playfield_3x_on:
      show_tokens:
        lights: Playfield_2X, Playfield_3X

  Skull_lanes_done{count==4}:
    Playfield_4x_on:
      show_tokens:
        lights: Playfield_2X, Playfield_3X, Playfield_4X

  Skull_lanes_done{count==5}:
    Playfield_5x_on:
      show_tokens:
        lights: Playfield_2X, Playfield_3X, Playfield_4X, Playfield_5X

  Skull_lanes_done{count>=6}:
    Playfield_10x_on:
      show_tokens:
        lights: Playfield_2X, Playfield_3X, Playfield_4X, Playfield_5X, Playfield_10X

sound_player:
  Skull_lanes_lit_complete:
    chant:
      action: play
      loops: 0