#config_version=5

mode:
  start_events: Jukebox_Start{current_player.pf_setlist==4}
  stop_events: ball_ended, mode_Song_Carousel_13_starting
  priority: 200

event_player:
  mode_Song_Carousel_10_started: play_random_song_4

random_event_player:
  play_random_song_4:
    force_different: true
    events:
      - Song_10
      - Song_11
      - Song_12

sound_player:
  mode_Song_Carousel_10_starting:
    Instrumental_track:
      action: stop
    Cult_track:
      action: stop
    Wild_track:
      action: stop
    Organizized_track:
      action: stop
    cheering:
      action: play
      loops: 0  

  mode_Song_Carousel_10_ending:
    Vampire:
      action: stop
    Destroy:
      action: stop
    Danger_track:
      action: stop

  Song_10:
    Vampire_track:
      action: play
      loops: -1

  Song_11:
    Destroy_track:
      action: play
      loops: -1

  Song_12:
    Danger_track:
      action: play
      loops: -1

variable_player:
  mode_Song_Carousel_10_started:
    pf_setlist:
      int: 5
      action: set
    pf_Album_4_Ready:
      int: 0
      action: set


show_player:
  Song_10: 
    vampire_track:
      loops: 0
      speed: 1

  Song_11: 
    destroy_track:
      loops: 0
      speed: 1

  Song_12: 
    danger_track:
      loops: 0
      speed: 1

  mode_Song_Carousel_10_started:
    Guitar_1K_On:
      show_tokens:
        lights: Guitar_1K
    Guitar_2K_On:
      show_tokens:
        lights: Guitar_2K
    Guitar_4K_On:
      show_tokens:
        lights: Guitar_4K
    Guitar_8K_On:
      show_tokens:
        lights: Guitar_8K