#config_version=5

mode:
  start_events: Jukebox_Start{current_player.pf_setlist==8}
  stop_events: ball_ended, mode_Red_starting
  priority: 200

event_player:
  mode_Song_Carousel_22_started: play_random_song_8

random_event_player:
  play_random_song_8:
    force_different: true
    events:
      - Song_22
      - Song_23
      - Song_24

sound_player:
  mode_Song_Carousel_22_starting:
    Instrumental_track:
      action: stop
    Love_track:
      action: stop
    Nobody_track:
      action: stop
    Walking_track:
      action: stop
    cheering:
      action: play
      loops: 0  
  mode_Song_Carousel_22_ending:
    Riot_track:
      action: stop
    Apathy_track:
      action: stop
    Return_track:
      action: stop

  Song_22:
    Riot_track:
      action: play
      loops: -1

  Song_23:
    Apathy_track:
      action: play
      loops: -1

  Song_24_:
    Return_track:
      action: play
      loops: -1

variable_player:
  mode_Song_Carousel_22_started:
    pf_setlist:
      int: 9
      action: set
    pf_Album_8_Ready:
      int: 0
      action: set

show_player:
  Song_22: 
    riot_track:
      loops: 0
      speed: 1

  Song_23: 
    apathy_track:
      loops: 0
      speed: 1

  Song_24: 
    return_track:
      loops: 0
      speed: 1