#config_version=5

mode:
  start_events: start_mode_Song_17
  stop_events: ball_ended, mode_Song_Carousel_19_starting
  priority: 200

sound_player:
  mode_Song_17_started:
    Ultra_track:
      action: play
      loops: -1
  ball_ending:
    Ultra_track:
      action: stop

slides:
  pick_Song17_slide: #Ultra Mega
    widgets:
      - type: image
        image: afd
    transition:
      type: move_in
      direction: right

slide_player:
  mode_Song_17_started: 
    pick_Song17_slide:
      expire: 5s
      target: dmd