#config_version=5

mode:
  start_events: start_mode_Song_17
  stop_events: mode_Song_Carousel_19_starting
  priority: 200

sound_player:
  mode_Song_17_started:
    Ultra_track:
      action: play
      loops: -1
  ball_ending:
    Ultra_track:
      action: stop


show_player:
  mode_Song_17_started: 
    ultra_track:
      loops: 0
      speed: 1