#config_version=5

mode:
  start_events: start_mode_Album_01
  stop_events: ball_ended, mode_Album_Award_02_starting
  priority: 200

show_player:
  mode_Album_01_started: 
    True_Force_Album:
      loops: 0
      speed: 1