#config_version=5

mode:
  start_events: ball_starting
  stop_events: ball_ended
  priority: 300

event_player:
  spider_shot_hit: award_random_clip

random_event_player:
  award_random_clip:
    force_different: true
    events:
      - clip_01
      - clip_02
      - clip_03
      - clip_04
      - clip_05
      - clip_06
      - clip_07
      - clip_09
      - clip_10
      - clip_11
      - clip_12
      - clip_13
      - clip_14
      - clip_15
      - clip_16
      - clip_17
      - clip_18
      - clip_19
      - clip_20
      - clip_21
      - clip_22
      - clip_23
      - clip_24
      - clip_25
      - clip_26
      - clip_27
      - clip_28
      - clip_29
      - clip_30
      - clip_31
      - clip_32

variable_player:
  spider_shot_hit:
    score: 5000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block

show_player:
  clip_01: 
    play_clip_01:
      loops: 0
      speed: 1

  clip_02: 
    play_clip_02:
      loops: 0
      speed: 1

  clip_03: 
    play_clip_03:
      loops: 0
      speed: 1

  clip_04: 
    play_clip_04:
      loops: 0
      speed: 1

  clip_05: 
    play_clip_05:
      loops: 0
      speed: 1

  clip_06: 
    play_clip_06:
      loops: 0
      speed: 1

  clip_07: 
    play_clip_07:
      loops: 0
      speed: 1

  clip_09: 
    play_clip_09:
      loops: 0
      speed: 1

  clip_10: 
    play_clip_10:
      loops: 0
      speed: 1

  clip_11: 
    play_clip_11:
      loops: 0
      speed: 1

  clip_12: 
    play_clip_12:
      loops: 0
      speed: 1

  clip_13: 
    play_clip_13:
      loops: 0
      speed: 1

  clip_14: 
    play_clip_14:
      loops: 0
      speed: 1

  clip_15: 
    play_clip_15:
      loops: 0
      speed: 1

  clip_16: 
    play_clip_16:
      loops: 0
      speed: 1

  clip_17: 
    play_clip_17:
      loops: 0
      speed: 1

  clip_18: 
    play_clip_18:
      loops: 0
      speed: 1

  clip_19: 
    play_clip_19:
      loops: 0
      speed: 1

  clip_20: 
    play_clip_20:
      loops: 0
      speed: 1

  clip_21: 
    play_clip_21:
      loops: 0
      speed: 1

  clip_22: 
    play_clip_22:
      loops: 0
      speed: 1

  clip_23: 
    play_clip_23:
      loops: 0
      speed: 1

  clip_24: 
    play_clip_24:
      loops: 0
      speed: 1

  clip_25: 
    play_clip_25:
      loops: 0
      speed: 1

  clip_26: 
    play_clip_26:
      loops: 0
      speed: 1

  clip_27: 
    play_clip_27:
      loops: 0
      speed: 1

  clip_28: 
    play_clip_28:
      loops: 0
      speed: 1

  clip_29: 
    play_clip_29:
      loops: 0
      speed: 1

  clip_30: 
    play_clip_30:
      loops: 0
      speed: 1

  clip_31: 
    play_clip_31:
      loops: 0
      speed: 1

  clip_32: 
    play_clip_32:
      loops: 0
      speed: 1