#config_version=5

mode:
  start_events: start_mode_Song_18
  stop_events: ball_ended, mode_Song_Carousel_19_starting
  priority: 200

sound_player:
  mode_Song_18_started:
    Revolution_track:
      action: play
      loops: -1
  ball_ending:
    Revolution_track:
      action: stop

slides:
  pick_Song18_slide: #Theme to a Fake Revolution
    widgets:
      - type: image
        image: transform
    transition:
      type: move_in
      direction: right

slide_player:
  mode_Song_18_started: 
    pick_Song18_slide:
      expire: 5s
      target: dmd