#config_version=5

mode:
  start_events: start_mode_Song_16_Carousel
  stop_events: mode_Song_16_start, mode_Song_17_start, mode_Song_18_start
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 300

mode_settings:
  selectable_items: Song16, Song17, Song18, 
  select_item_events: sw_Both_Flippers
  next_item_events: sw_right_flipper_active
  previous_item_events: sw_left_flipper_active

queue_relay_player:
  balldevice_bd_right_saucer_eject_attempt:
    post: start_mode_Song_16_Carousel
    wait_for: mode_Song_16_start, mode_Song_17_start, mode_Song_18_start

slide_player:
  carousel_Song16_highlighted: select_Song16
  carousel_Song17_highlighted: select_Song17
  carousel_Song18_highlighted: select_Song18

slides:
  select_Song16: #The End of Everything
    widgets:
      - type: image
        image: afd
    transition:
      type: move_in
      direction: right
  select_Song17: #Mega Kung Fu Radio
    widgets:
      - type: image
        image: mkfr
    transition:
      type: move_in
      direction: right
  select_Song18: #Theme To A Fake Revolution
    widgets:
      - type: image
        image: transform
    transition:
      type: move_in
      direction: right
 
event_player:
  select_Song16: mode_Song_16_start
  select_Song17: mode_Song_17_start
  select_Song18: mode_Song_18_start  