#config_version=5

mode:
  start_events: start_mode_Album_03
  stop_events: ball_ended, mode_Album_Award_02_starting
  priority: 200

show_player:
  mode_Album_03_started: 
    MKFR_Album:
      loops: 0
      speed: 1