#config_version=5

mode:
  start_events: start_mode_Song_19_Carousel
  stop_events: mode_Song_19_start, mode_Song_20_start, mode_Song_21_start
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 300

mode_settings:
  selectable_items: Song19, Song20, Song21, 
  select_item_events: sw_Both_Flippers
  next_item_events: sw_right_flipper_active
  previous_item_events: sw_left_flipper_active

queue_relay_player:
  balldevice_bd_right_saucer_eject_attempt:
    post: start_mode_Song_19_Carousel
    wait_for: mode_Song_19_start, mode_Song_20_start, mode_Song_21_start

slide_player:
  carousel_Song19_highlighted: select_Song19
  carousel_Song20_highlighted: select_Song20
  carousel_Song21_highlighted: select_Song21

slides:
  select_Song19: #You're Gonna Love It If You Like Or Not
    widgets:
      - type: image
        image: bof
    transition:
      type: move_in
      direction: right
  select_Song20: #Nobody's Real
    widgets:
      - type: image
        image: ttsr
    transition:
      type: move_in
      direction: right
  select_Song21: #Walking Disaster
    widgets:
      - type: image
        image: dwye
    transition:
      type: move_in
      direction: right 
event_player:
  select_Song19: mode_Song_19_start
  select_Song20: mode_Song_20_start
  select_Song21: mode_Song_21_start  