#config_version=5

mode:
  start_events: Jukebox_Start{current_player.pf_setlist==6}   
  stop_events: ball_ended, mode_Song_Carousel_19_starting
  priority: 200

event_player:
  mode_Song_Carousel_16_started: play_random_song_6

random_event_player:
  play_random_song_6:
    force_different: true
    events:
      - Song_16
      - Song_17
      - Song_18

sound_player:
  mode_Song_Carousel_16_starting:
    Instrumental_track:
      action: stop
    Hey_track:
      action: stop
    Villain_track:
      action: stop
    Sid_track:
      action: stop
    cheering:
      action: play
      loops: 0  
  mode_Song_Carousel_16_ending:
    Everything_track:
      action: stop
    Ultra_track:
      action: stop
    Revolution_track:
      action: stop

  Song_16:
    Everything_track:
      action: play
      loops: -1

  Song_17:
    Ultra_track:
      action: play
      loops: -1

  Song_18:
    Revolution_track:
      action: play
      loops: -1

variable_player:
  mode_Song_Carousel_16_started:
    pf_setlist:
      int: 7
      action: set
    pf_Album_6_Ready:
      int: 0
      action: set


show_player:
  Song_16: 
    everything_track:
      loops: 0
      speed: 1

  Song_17: 
    ultra_track:
      loops: 0
      speed: 1

  Song_18: 
    revolution_track:
      loops: 0
      speed: 1