#config_version=5

mode:
  start_events: start_mode_Song_15
  stop_events: mode_Song_Carousel_16_starting
  priority: 200

sound_player:
  mode_Song_15_started:
    Sid_track:
      action: play
      loops: -1
  ball_ending:
    Sid_track:
      action: stop

show_player:
  mode_Song_15_started: 
    sid_track:
      loops: 0
      speed: 1