#config_version=5

mode:
  start_events: start_mode_Song_15
  stop_events: ball_ended, mode_Song_Carousel_16_starting
  priority: 200

sound_player:
  mode_Song_15_started:
    Sid_track:
      action: play
      loops: -1
  ball_ending:
    Sid_track:
      action: stop

slides:
  pick_Song15_slide: #Sid Vicious In A Dress
    widgets:
      - type: image
        image: nw
    transition:
      type: move_in
      direction: right

slide_player:
  mode_Song_15_started: 
    pick_Song15_slide:
      expire: 5s
      target: dmd