#config_version=5

mode:
  start_events: start_mode_Member_13
  stop_events: ball_ended, mode_Member_Award_05_starting
  priority: 200

show_player:
  mode_Member_13_started: 
    BSRS_Album:
      loops: 0
      speed: 1