#config_version=5

mode_settings:
   display_delay_ms: 1s
   hurry_up_delay_ms: 0
   bonus_entries:
    - event: pf_spider_bonus
      score: 500
    - event: pf_Jukebox_Hits
      score: 1000 * (current_player.pf_Jukebox_Hits + 2)
    - event: pf_album_bonus
      score: 500
    - event: pf_PM5K_bonus
      score: 500

slide_player:
  mode_bonus_started: bonus_start_slide
  pf_spider_bonus: spider_bonus_slide
  pf_Jukebox_Hits: jukebox_bonus_slide
  pf_album_bonus: album_bonus_slide
  pf_PM5K_bonus: PM5K_bonus_slide   
  bonus_total: bonus_total_slide

slides:
  bonus_start_slide:
    widgets:
      - type: text
        text: Bonus
  spider_bonus_slide:
    - type: text
      text: "Spiders Caught: (player|pf_spider_bonus)"
      anchor_y: bottom
      font_size: 15
    - type: text
      text: (score)
      font_size: 150
      anchor_y: top
  jukebox_bonus_slide:
    - type: text
      text: "Jukebox Hits: (player|pf_Jukebox_Hits)"
      font_size: 15
      anchor_y: bottom
    - type: text
      text: (score)
      anchor_y: top
      font_size: 15
  album_bonus_slide:
    - type: text
      text: "Albums Collected: (player|pf_album_bonus)"
      font_size: 15
      anchor_y: bottom
    - type: text
      text: (score)
      anchor_y: top
      font_size: 15
  PM5K_bonus_slide:
    - type: text
      text: "Concerts Rocked: (player|pf_PM5K_bonus)"
      font_size: 15
      anchor_y: bottom
    - type: text
      text: (score)
      anchor_y: top
      font_size: 15
  bonus_total_slide:
    - type: text
      text: "Total Bonus"
      anchor_y: bottom
      font_size: 15
    - type: text
      text: (score)
      anchor_y: top
      font_size: 15

sound_player:
  bonus_start:
    riff_01:
      action: play
      loops: 0
