#config_version=5

mode:
  start_events: Hurry_Up_Ready
  stop_events: ball_ended, spider_shot_hit, timer_lb_spider_hurry_up_stopped
  priority: 500

timers:

  lb_spider_hurry_up:
    start_value: 30
    end_value: 0
    direction: down
    tick_interval: .25s
    control_events:
      - event: mode_hurry_up_started
        action: start
      - event: hurry_up_slide_removed
        action: pause
      - event: spider_shot_hit
        action: reset
      - event: timer_lb_spider_hurry_up_stopped
        action: reset

variable_player:

  timer_lb_spider_hurry_up_started:
    temp_hurryup_value:
      action: set
      int: 120000
  spider_shot_hit:
    score: current_player.temp_hurryup_value * current_player.pf_multiplier * current_player.pf_MBall_multiplier
    temp_hurryup_value:
     action: add
     int: 120000
  timer_lb_spider_hurry_up_tick{current_player.temp_hurryup_value > 0}:
    temp_hurryup_value: -2500 
  timer_lb_spider_hurry_up_stopped:
    temp_hurryup_value:
      int: 0
      action: set

slide_player:
  timer_lb_spider_hurry_up_started: hurry_up_slide
  spider_shot_hit:
    hurry_up_slide:
      action: remove
  timer_lb_spider_hurry_up_stopped:
    hurry_up_slide:
      action: remove

slides:
  hurry_up_slide:
    widgets:
      - type: text
        text: (temp_hurryup_value)
        number_grouping: true
        min_digits: 2
        font_size: 20
        y: 18
      - type: text
        text: PLAYER (number)
        y: 0
        x: 10
        font_size: 10
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 0
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 10
      - type: video
        video: radar
        volume: 0
        auto_play: true
        end_behavior: loop

sound_player:
  timer_lb_spider_hurry_up_started:
    hurry_up:
      action: play
      loops: -1

  spider_shot_hit:
    hurry_up:
      action: stop

  timer_lb_spider_hurry_up_stopped:
    hurry_up:
      action: stop

  mode_hurry_up_stopping:
    hurry_up:
      action: stop

show_player:
  timer_lb_spider_hurry_up_started:
    flash: 
      loops: -1
      speed: 10
      show_tokens:
        lights: Hurry_Up

  spider_shot_hit:
    flash: 
      loops: 0
      speed: 4
      show_tokens:
        lights: Hurry_Up
