#config_version=5

mode:
  start_events: Jukebox_Start{current_player.pf_setlist==1}
  stop_events: ball_ended, mode_Song_Carousel_4_starting
  priority: 200

event_player:
  mode_Song_Carousel_1_started: play_random_song_1

random_event_player:
  play_random_song_1:
    force_different: true
    events:
      - Song_1
      - Song_2
      - Song_3

sound_player:
  mode_Song_Carousel_1_starting:
    Instrumental_track:
      action: stop
    Apathy_track:
      action: stop
    Riot_track:
      action: stop
    Return_track:
      action: stop
    cheering:
      action: play
      loops: 0      

  mode_Song_Carousel_1_ending:
    Voices_track:
      action: stop
    Showme_track:
      action: stop
    Invade_track:
      action: stop

  Song_1:
    Voices_track:
      action: play
      loops: -1

  Song_2:
    Invade_track:
      action: play
      loops: -1

  Song_3:
    Showme_track:
      action: play
      loops: -1

variable_player:
  mode_Song_Carousel_1_started:
    pf_setlist:
      int: 2
      action: set

show_player:
  Song_1: 
    footsteps_track:
      loops: 0
      speed: 1

  Song_2: 
    invade_track:
      loops: 0
      speed: 1

  Song_3: 
    showme_track:
      loops: 0
      speed: 1