#config_version=5

mode:
  start_events: start_mode_Song_16
  stop_events: mode_Song_Carousel_19_starting
  priority: 200

sound_player:
  mode_Song_16_started:
    Everything_track:
      action: play
      loops: -1
  ball_ending:
    Everything_track:
      action: stop

show_player:
  mode_Song_16_started: 
    everything_track:
      loops: 0
      speed: 1