#config_version=5

mode:
  start_events: start_mode_Song_16
  stop_events: ball_ended, mode_Song_Carousel_19_starting
  priority: 200

sound_player:
  mode_Song_16_started:
    Everything_track:
      action: play
      loops: -1
  ball_ending:
    Everything_track:
      action: stop

slides:
  pick_Song16_slide: #The End of Everything
    widgets:
      - type: image
        image: afd
    transition:
      type: move_in
      direction: right

slide_player:
  mode_Song_16_started: 
    pick_Song16_slide:
      expire: 5s
      target: dmd