#config_version=5

mode:
  start_events: start_mode_Song_22
  stop_events: ball_ended, mode_Red_starting
  priority: 200

sound_player:
  mode_Song_22_started:
    Riot_track:
      action: play
      loops: -1
  ball_ending:
    Riot_track:
      action: stop

slides:
  pick_Song22_slide: #Riot Time
    widgets:
      - type: image
        image: dwye
    transition:
      type: move_in
      direction: right

slide_player:
  mode_Song_22_started: 
    pick_Song22_slide:
      expire: 5s
      target: dmd