#config_version=5

mode:
  start_events: start_mode_Album_09
  stop_events: ball_ended, mode_Album_Award_04_starting
  priority: 200

show_player:
  mode_Album_09_started: 
    TGTBTUV1_Album:
      loops: 0
      speed: 1