#config_version=5

mode:
  start_events: Jukebox_Start{current_player.pf_setlist==2}
  stop_events: ball_ended, mode_Song_Carousel_7_starting
  priority: 200

event_player:
  mode_Song_Carousel_4_started: play_random_song_2

random_event_player:
  play_random_song_2:
    force_different: true
    events:
      - Song_4
      - Song_5
      - Song_6

sound_player:
  mode_Song_Carousel_4_starting:
    Instrumental_track:
      action: stop
    Voices_track:
      action: stop
    Showme_track:
      action: stop
    Invade_track:
      action: stop
    cheering:
      action: play
      loops: 0  

  mode_Song_Carousel_4_ending:
    Supernova_track:
      action: stop
    Free_track:
      action: stop
    Human_track:
      action: stop

  Song_4:
    Human_track:
      action: play
      loops: -1

  Song_5:
    Supernova_track:
      action: play
      loops: -1

  Song_6:
    Free_track:
      action: play
      loops: -1

variable_player:

  mode_Song_Carousel_4_started:
    pf_setlist:
      int: 3
      action: set
    pf_Album_2_Ready:
      int: 0
      action: set

show_player:
  Song_4: 
    human_track:
      loops: 0
      speed: 1

  Song_5: 
    supernova_track:
      loops: 0
      speed: 1

  Song_6: 
    free_track:
      loops: 0
      speed: 1

  mode_Song_Carousel_4_started:
    Guitar_2K_On:
      show_tokens:
        lights: Guitar_2X