#config_version=5

mode:
  start_events: reset_PM5K{current_player.pf_setlist==2}
  stop_events: ball_ended, mode_Song_Carousel_7_starting
  priority: 200

event_player:
  mode_Song_Carousel_4_started: play_random_song_2

random_event_player:
  play_random_song_2:
    force_different: true
    events:
      - start_mode_Song_4
      - start_mode_Song_5
      - start_mode_Song_6

sound_player:
  mode_Song_Carousel_4_starting:
    Instrumental_track:
      action: stop
    Voices_track:
      action: stop
    Showme_track:
      action: stop
    Invade_track:
      action: stop
  mode_Song_Carousel_4_ending:
    Supernova_track:
      action: stop
    Free_track:
      action: stop
    Human_track:
      action: stop

variable_player:
  mode_Song_Carousel_4_started:
    pf_setlist:
      int: 3
      action: set
    pf_Album_2_Ready:
      int: 0
      action: set