#config_version=5

mode:
  start_events: right_rollover_shot_hit
  stop_events: timer_r_rollover_stopped

timers:
  r_rollover:
    debug: True
    start_value: 10
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: yes
    control_events:
      - event: right_rollover_shot_hit
        action: reset

variable_player:
  left_return_shot_hit:
    score: 10000 * current_player.pf_multiplier|block
  left_25K_shot_hit:
    score: 25000 * current_player.pf_multiplier|block
  left_rollover_shot_hit:
    score: 50000 * current_player.pf_multiplier|block
