#config_version=5

mode:
  start_events: start_mode_Song_21
  stop_events: mode_Song_Carousel_22_starting
  priority: 200

sound_player:
  mode_Song_21_started:
    Walking_track:
      action: play
      loops: -1
  ball_ending:
    Walking_track:
      action: stop


show_player:
  mode_Song_21_started: 
    walking_track:
      loops: 0
      speed: 1