#config_version=5

mode:
  start_events: start_mode_Song_5
  stop_events: ball_ended, mode_Song_Carousel_7_starting
  priority: 200

sound_player:
  mode_Song_5_started:
    Supernova_track:
      action: play
      loops: -1
  ball_ending:
    Supernova_track:
      action: stop

show_player:
  mode_Song_5_started: 
    supernova_track:
      loops: 0
      speed: 1