#config_version=5

mode:
  start_events: start_mode_Song_4_Carousel
  stop_events: mode_Song_4_start, mode_Song_5_start, mode_Song_6_start
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 300

mode_settings:
  selectable_items: Song4, Song5, Song6, 
  select_item_events: sw_Both_Flippers
  next_item_events: sw_right_flipper_active
  previous_item_events: sw_left_flipper_active

queue_relay_player:
  balldevice_bd_right_saucer_eject_attempt:
    post: start_mode_Song_4_Carousel
    wait_for: mode_Song_4_start, mode_Song_5_start, mode_Song_6_start

slide_player:
  carousel_Song4_highlighted: select_Song4
  carousel_Song5_highlighted: select_Song5
  carousel_Song6_highlighted: select_Song6

slides:
  select_Song4: #How To Be A Human
    widgets:
      - type: image
        image: bof
    transition:
      type: move_in
      direction: right
  select_Song5: #Supernova Goes Pop
    widgets:
      - type: image
        image: ttsr
    transition:
      type: move_in
      direction: right
  select_Song6: #Free
    widgets:
      - type: image
        image: transform
    transition:
      type: move_in
      direction: right
 
event_player:
  select_Song4: mode_Song_4_start
  select_Song5: mode_Song_5_start
  select_Song6: mode_Song_6_start  