#config_version=5

mode:
  start_events: start_mode_Pick_Song{player_variable.setlist==1}
  stop_events: player_variable{setlist==2}
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 200

mode_settings:
  selectable_items: Song1, Song2, Song3
  select_item_events: sw_left_slingshot_active
  next_item_events: sw_right_flipper_active
  previous_item_events: sw_left_flipper_active

slide_player:
  carousel_Song1_highlighted: pick_Song1
  carousel_Song2_highlighted: pick_Song2
  carousel_Song3_highlighted: pick_Song3

slides:
  pick_Song1: #Footsteps and Voices
    widgets:
      - type: image
        image: nw
    transition:
      type: move_in
      direction: right
  pick_Song2: #Show Me What You've Got
    widgets:
      - type: image
        image: sotoson
    transition:
      type: move_in
      direction: right
  pick_Song3: #Invade, Destroy, Repeat
    widgets:
      - type: image
        image: bof
    transition:
      type: move_in
      direction: right

event_player:
  select_Song1: mode_Song_1_start
  select_Song2: mode_Song_2_start
  select_Song3: mode_Song_3_start

  player_variable:
    select_Song1:
      player_variable.setlist:
        int: 2
        action: set