#config_version=5

mode:
  start_events: balldevice_bd_left_saucer_ball_entered{current_player.pf_album==6}  
  stop_events: ball_ended, mode_Album_Award_01_starting
  priority: 200

variable_player:
  mode_Album_Award_Jackpot_started:
    pf_album:
      int: 1
      action: set

  balldevice_bd_left_saucer_ball_entered:
    score: 10000 * current_player.pf_multiplier
