#config_version=5

mode:
  start_events: start_mode_Song_6
  stop_events: mode_Song_Carousel_7_starting
  priority: 200

sound_player:
  mode_Song_6_started:
    Free_track:
      action: play
      loops: -1
  ball_ending:
    Free_track:
      action: stop

show_player:
  mode_Song_6_started: 
    free_track:
      loops: 0
      speed: 1