#config_version=5

ball_devices:
  bd_drain:
    ball_switches: s_outhole
    eject_coil: c_outhole
    eject_targets: bd_trough
    tags: drain, outhole
    
  bd_trough:
    ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_5
    eject_coil: c_ball_eject
    tags: trough, home

  bd_left_saucer: 
    ball_switches: s_left_saucer
    eject_coil: c_left_saucer
    eject_timeouts: 2s
    tags: saucer

  bd_right_saucer:
    ball_switches: s_right_saucer
    eject_coil: c_right_saucer
    eject_timeouts: 2s
    tags: saucer

  bd_ramp_load:
    entrance_switch: s_load_chamber
    eject_coil: c_pin_down
    ball_capacity: 5
  
drop_targets:
  bd_drop_target:
    switch: s_ramp_drop_target

drop_target_banks:
  ramp_drop_target:
    drop_targets: bd_drop_target
    reset_coils: c_drop_target
    reset_events:
      - machine_reset_phase_3
      - ball_searching
      - ball_ending
    reset_on_complete: 10s