#config_version=5

displays:
  window:
    width: 600
    height: 200
  dmd:
    width: 128
    height: 32
    default: true

window:
  width: 600
  height: 200
  title: Mission Pinball Framework - Powerman 5000
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: window

slides:
  window_slide_1:
  - type: display
    width: 512
    height: 128
    effects:
      - type: dmd
        dot_color: 00ff00
        background_color: 000000
  - type: text
    style: tall title
    text: MISSION PINBALL FRAMEWORK
    anchor_y: top
    y: top-3
    font_size: 30
    color: white
  - type: rectangle
    width: 514
    height: 130
    color: 444444
  - type: text
    style: tall title
    text: POWERMAN 5000
    anchor_x: right
    anchor_y: bottom
    y: bottom+3
    x: right-42
    font_size: 30
    color: red

  waiting_for_connection:
    widgets:
      - type: text
        text: WAITING FOR MPF CONNECTION

  asset_status:
    widgets:
      - type: text
        text: "LOADING ASSETS: (percent)%"

  machine_slide_01:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 20
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 10
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 10

slide_player:
  #mc_ready:
  #  window_slide_1:
  #    target: window
  #    loading_assets: asset_status

  mode_base_started:
    machine_slide_01:
      priority: 100
