#config_version=5
# powerman

machine:
    balls_installed: 5
    min_balls: 1

mpf-mc:
    fps: 60

virtual_platform_start_active_switches: s_trough_1 s_trough_2 s_trough_3 s_trough_4 s_trough_5

window:
    width: 600
    height: 200
    title: Mission Pinball Framework - Powerman 5000
    resizable: true
    fullscreen: false
    borderless: false
    exit_on_escape: true
    source_display: window

displays:
    window:
        width: 600
        height: 200
    dmd:
        width: 128
        height: 32
        default: true

switches:
    s_left_flipper:
        number: 0 
        tags: left_flipper

    s_right_flipper:
        number: 71
        tags: right_flipper

    s_left_saucer:
        number: 1
        tags: 

    s_right_saucer:
        number: 2
        tags: 

    s_load_chamber:
        number: 3
        tags: 

    s_eject_chamber:
        number: 4
        tags: playfield_active, Bonus_Multiplier

    s_cabinet_left:
        number: 5
        tags: playfield_active

    s_credit:
        number: 6
        tags: start

    s_cabinet_right:
        number: 7
        tags: playfield_active

    s_outhole:
        number: 8
        tags: 

    s_coins_right:
        number: 9
        tags: playfield_active

    s_coins_left:
        number: 10
        tags: playfield_active

    s_coins_middle:
        number: 11
        tags: playfield_active

    s_left_return_lane:
        number: 12
        tags: playfield_active

    s_right_return_lane:
        number: 13
        tags: playfield_active

    s_slam:
        number: 14
        tags: playfield_active

    s_tilt:
        number: 15
        tags: playfield_active

    s_ramp_drop_target:
        number: 16
        tags: 

    s_left_bumper:
        number: 17
        tags:  jet

    s_middle_bumper:
        number: 18
        tags: jet

    s_right_bumper:
        number: 19
        tags: jet

    s_right_slingshot:
        number: 20
        tags: 

    s_left_slingshot:
        number: 21
        tags: 

    s_top_lane_J:
        number: 22
        tags: playfield_active, JAM_lanes

    s_top_lane_A:
        number: 23
        tags: playfield_active, JAM_lanes

    s_top_lane_M:
        number: 24
        tags: playfield_active, JAM_lanes

    s_left_outlane:
        number: 25
        tags: playfield_active

    s_right_outlane:
        number: 26
        tags: playfield_active

    s_top_25K_lane:
        number: 27
        tags: playfield_active

    s_top_50K_lane:
        number: 28
        tags: playfield_active

    s_left_rollover:
        number: 29
        tags: playfield_active

    s_right_rollover:
        number: 30
        tags: playfield_active

    s_left_25K_target:
        number: 31
        tags: playfield_active

    s_right_25K_target:
        number: 32
        tags: playfield_active

    s_center_target:
        number: 33
        tags: playfield_active

    s_metal_target:
        number: 34
        tags: playfield_active

    s_heavy_target:
        number: 35
        tags: playfield_active

    s_trough_5:
        number: 36
        tags: 

    s_trough_4:
        number: 37
        tags: 

    s_trough_3:
        number: 38
        tags: 

    s_trough_2:
        number: 39
        tags:

    s_trough_1:
        number: 40
        tags: 

lights:
    l_rock_again:
        number: 1

    l_bonus_128K:
        number: 2

    l_bonus_held:
        number: 3

    l_bonus_64K:
        number: 4

    l_right_rollover:
        number: 5

    l_bonus_32K:
        number: 6

    l_left_rollover:
        number: 7

    l_bonus_16K:
        number: 8

    l_right_return:
        number: 9

    l_bonus_8K:
        number: 10

    l_left_return:
        number: 11

    l_bonus_4K:
        number: 12

    l_right_outlane:
        number: 13

    l_bonus_2K:
        number: 14

    l_left_outlane:
        number: 15

    l_bonus_1K:
        number: 16

    l_power_amp_3_top:
        number: 17
        tags: AMP_Bonus_X

    l_meltdown:
        number: 18

    l_power_amp_2_mid:
        number: 19
        tags: AMP_Bonus_X

    l_ramp_100K:
        number: 20

    l_power_amp_1_bottom:
        number: 21
        tags: AMP_Bonus_X

    l_bonus_6X:
        number: 22
        tags: Bonus_6X

    l_bonus_5X:
        number: 23
        tags: Bonus_5X

    l_bonus_4X:
        number: 24
        tags: Bonus_4X

    l_snare_drum_3_right:
        number: 25
        tags: Snare_Drum_3

    l_bonus_3X:
        number: 26
        tags: Bonus_3X

    l_snare_drum_2_mid:
        number: 27

    l_bonus_2X:
        number: 28
        tags: Bonus_2X

    l_snare_drum_1_left:
        number: 29

    l_booster_3_top:
        number: 30

    l_jam_M:
        number: 31
        tags: JAM_lanes

    l_booster_2_mid:
        number: 32

    l_jam_A:
        number: 33
        tags: JAM_lanes

    l_booster_1_bottom:
        number: 34

    l_jam_J:
        number: 35
        tags: JAM_lanes

    l_value_10X:
        number: 36
        tags: Playfield_10X

    l_top_box_right:
        number: 37

    l_value_5X:
        number: 38
        tags: Playfield_5X

    l_value_4X:
        number: 39
        tags: Playfield_4X

    l_right_bumper:
        number: 40

    l_value_3X:
        number: 41
        tags: Playfield_3X

    l_middle_bumper:
        number: 42

    l_value_2X:
        number: 43
        tags: Playfield_2X

    l_left_bumper:
        number: 44

    l_top_box_mid:
        number: 45

    l_special:
        number: 46

    l_top_box_left:
        number: 47

    l_extra_ball:
        number: 48

    l_top_lane_50K:
        number: 49

    l_qualify_hold_bonus:
        number: 50

    l_top_lane_25K:
        number: 51

    l_level_5:
        number: 52

    l_right_collect_bonus:
        number: 53

    l_level_4:
        number: 54

    l_left_collect_bonus:
        number: 55

    l_level_3:
        number: 56

    l_right_25K_target:
        number: 57

    l_level_2:
        number: 58

    l_left_25K_target:
        number: 59

    l_level_1:
        number: 60

    l_heavy_y:
        number: 61

    l_metal_l:
        number: 62

    l_heavy_v:
        number: 63

    l_metal_a:
        number: 64

    l_heavy_a:
        number: 65

    l_metal_t:
        number: 66

    l_heavy_e:
        number: 67

    l_metal_e:
        number: 68

    l_heavy_h:
        number: 69

    l_metal_m:
        number: 70

coils:
    c_flipper_left_main:
        number: 0
        default_pulse_ms: 20
    c_flipper_left_hold:
        number: 1
        allow_enable: true
    c_flipper_right_main:
        number: 2
        default_pulse_ms: 20
    c_flipper_right_hold:
        number: 3
        allow_enable: true
    c_trough_eject:
        number: 4
        allow_enable: true

    c_left_bumper:
        number: c01
        label:
        tags:
        default_pulse_ms: 25
    c_middle_bumper:
        number: c02
        label:
        tags:
        default_pulse_ms: 25
    c_right_bumper:
        number: c03
        label:
        tags:
        default_pulse_ms: 25
    c_left_slingshot:
        number: c04
        label:
        tags:
        default_pulse_ms: 30
    c_right_slingshot:
        number: c05
        label:
        tags:
        default_pulse_ms: 30
        max_hold_power: 0.5
    c_left_saucer:
        number: c06
        label:
        tags:
    c_right_saucer:
        number: c07
        label:
        tags:
    c_drop_target:
        number: c08
        label:
        tags:
    #name
    #    number: c09
    #    label:
    #    tags:
    c_pin_up:
        number: c10
        label:
        tags:
    c_pin_down:
        number: c11
        label:
        tags:
    c_ball_eject:
        number: c12
        label:
        tags:
        default_pulse_ms: 20
    #name:
     #    number: c13
     #    label:
     #    tags:
    c_outhole:
        number: c14
        label:
        tags:
        default_pulse_ms: 20
    c_knocker:
        number: c15
        label:
        tags:    
    c_backbox_light:
        number: c16
        label:
        tags:
    c_top_light:
        number: c17
        label:
        tags:
    c_flipper_backbox:
        number: c18
        label:
        tags:
    #name:
    #    number: c19
    #    label:
    #    tags: 

ball_devices:

    bd_drain:
        ball_switches: s_outhole
        eject_coil: c_outhole
        eject_targets: bd_trough
        tags: drain, outhole

    bd_trough:
        ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_5
        eject_coil: c_ball_eject
        tags: trough, home

    bd_left_saucer:
        tags: left saucer, meltdown, collect 
        ball_switches: s_left_saucer
        eject_coil: c_left_saucer
        eject_timeouts: 2s

    bd_right_saucer:
        tags: right saucer, hold bonus, collect 
        ball_switches: s_right_saucer
        eject_coil: c_right_saucer
        eject_timeouts: 2s

    bd_ramp_drop_target:
        tags: drop, ramp
        ball_switches: s_ramp_drop_target
        eject_coil: c_drop_target

autofire_coils:
    left_slingshot:
        coil: c_left_slingshot
        switch: s_left_slingshot

    right_slingshot:
        coil: c_right_slingshot
        switch: s_right_slingshot

    left_jet:
        coil: c_left_bumper
        switch: s_left_bumper

    mid_jet:
        coil: c_middle_bumper
        switch: s_middle_bumper

    right_jet:
        coil: c_right_bumper
        switch: s_right_bumper

flippers: 
    left_flipper: 
        main_coil: c_flipper_left_main 
        hold_coil: c_flipper_left_hold 
        activation_switch: s_left_flipper
        
    right_flipper: 
        main_coil: c_flipper_right_main 
        hold_coil: c_flipper_right_hold 
        activation_switch: s_right_flipper

playfields:
    playfield:
        tags: default
        default_source_device: bd_trough
      
sound_system:
    tracks:
        voice:
            volume: 1
            priority: 2
            simultaneous_sounds: 1
            preload: true
        sfx:
            volume: 1
            priority: 1
            preload: true
            simultaneous_sounds: 7
        music:
            volume: 0.5
            simultaneous_sounds: 1
    buffer: 2048  # previous value was 512
    frequency: 44100
    channels: 1
    master_volume: 1
    enabled: true

assets:
    sounds:
        default:
            preload: yes
        music:
            track: music
        sfx:
            track: sfx
            load: on_demand
        voice:
            track: voice
            load: on_demand

sounds:
    Invade:
        file: Invade.flac
        priority: 100

    Bombshell_track:
        file: Bombshell.flac
        priority: 200


slides:
    window_slide_1:
    - type: display
      width: 512
      height: 128
      effects:
        - type: dmd
          dot_color: 00ff00
          background_color: 000000
    - type: text
      style: tall title
      text: MISSION PINBALL FRAMEWORK
      anchor_y: top
      y: top-3
      font_size: 30
      color: white
    - type: rectangle
      width: 514
      height: 130
      color: 444444
    - type: text
      style: tall title
      text: POWERMAN 5000
      anchor_x: right
      anchor_y: bottom
      y: bottom+3
      x: right-42
      font_size: 30
      color: red

    waiting_for_connection:
    - type: text
      text: WAITING FOR MPF CONNECTION

    asset_status:
    - type: text
      text: "LOADING ASSETS: (percent)%"

slide_player:
        mc_ready:
            window_slide_1:
                target: window
        loading_assets: asset_status