#config_version=5
# powerman

mpf-mc:
    fps: 60

virtual_platform_start_active_switches: s_trough_1 s_trough_2 s_trough_3 s_trough_4 s_trough_5

sound_system:
    tracks:
        voice:
            volume: 1
            priority: 2
            simultaneous_sounds: 1
            preload: true
        sfx:
            volume: 1
            priority: 1
            preload: true
            simultaneous_sounds: 7
        music:
            volume: 0.5
            simultaneous_sounds: 1
    buffer: 2048  # previous value was 512
    frequency: 44100
    channels: 1
    master_volume: 1
    enabled: true

assets:
    sounds:
        default:
            preload: yes
        music:
            track: music
        sfx:
            track: sfx
            load: on_demand
        voice:
            track: voice
            load: on_demand