#config_version=5
keyboard:
  s:
    switch: s_credit
  1:
    switch: s_trough_1
    toggle: true

  z:
    switch: s_left_flipper
  /:
    switch: s_right_flipper
  
  d:
    switch: s_top_lane_R
  f:
    switch: s_top_lane_C
  g:
    switch: s_top_lane_L
  a:
    switch: s_PM5K_target
  h:
    switch: s_album_target
  7:
    switch: s_left_bumper
  8:
    switch: s_middle_bumper
  9:
    switch: s_right_bumper
  k:
    switch: s_right_saucer
  j:
    switch: s_center_target

  o:
    switch: s_load_chamber
  p:
    switch: s_eject_chamber