#config_version=5

modes:
- base
- Skull_rollover 
- ALBUM_made 
- Super_Pops
- Song_1
- Song_2
- Song_3
- Song_Carousel_1
- Song_Carousel_4
- Song_4
- Song_5
- Song_6
- Song_Carousel_7
- Song_7
- Song_8
- Song_9
- Song_Carousel_10
- Song_10
- Song_11
- Song_12
- Song_Carousel_13
- Song_13
- Song_14
- Song_15
- Song_Carousel_16
- Song_16
- Song_17
- Song_18
- Song_Carousel_19
- Song_19
- Song_20
- Song_21
- Song_Carousel_22
- Song_22
- Song_23
- Song_24
#- Album_Award_01
- drop_target_ramp_entrance
- Spider
- bonus
- Collide_Multiball
- match
- high_score
- rollovers
- hurry_up