#config_version=5

modes:
- base
- Skull_rollover 
- AMP_Bonus_X 
- PM5K_made 
- ALBUM_made 
- Super_Pops
- Song_1
- Song_2
- Song_3
- Song_Carousel_1
- Song_Carousel_4
- Song_4
- Song_5
- Song_6
- Song_Carousel_7
- Song_7
- Song_8
- Song_9
- Song_Carousel_10
- Song_10
- Song_11
- Song_12
- Song_Carousel_13
- Song_13
- Song_14
- Song_15
- Song_Carousel_16
- Song_16
- Song_17
- Song_18
- Song_Carousel_19
- Song_19
- Song_20
- Song_21
- Song_Carousel_22
- Song_22
- Song_23
- Song_24
- Red
- Album_Award_01
- Album_Award_02
- Album_Award_03
- Album_Award_04
- Album_Award_Jackpot
- Album_01
- Album_02
- Album_03
- Album_04
- Album_05
- Album_06
- Album_07
- Album_08
- Album_09
- Album_10
- Album_11
- Album_12
- Left_Rollover
- Right_Rollover
- drop_target_ramp_entrance
- Member_Award_01
- Member_Award_02
- Member_Award_03
- Member_Award_04
- Member_Award_05
- Member_Award_Jackpot
- Member_01
- Member_02
- Member_03
- Member_04
- Member_05
- Member_06
- Member_07
- Member_08
- Member_09
- Member_10
- Member_11
- Member_12
- Member_13
- Member_14
- Member_15
- Member_16
- Member_17
- Member_18
- Member_19
- Member_20