#config_version=5

modes:
- base
- Skull_rollover 
- ALBUM_made 
- Super_Pops
- Song_Carousel_1
- Song_Carousel_4
- Song_Carousel_7
- Song_Carousel_10
- Song_Carousel_13
- Song_Carousel_16
- Song_Carousel_19
- Song_Carousel_22
- drop_target_ramp_entrance
- Spider
- bonus
- Collide_Multiball
- match
- high_score
- rollovers
- hurry_up
- setlist_hurry_up