#config_version=5

modes:
- base
- Skull_rollover 
- AMP_Bonus_X 
- PM5K_made 
- ALBUM_made 
- Super_Pops
- Pick_Song
- Song_1_Carousel
- Song_1
- Song_2
- Song_3

#- Song_4_Carousel
#- Song_7_Carousel
#- Song_10_Carousel
#- Song_13_Carousel
#- Song_16_Carousel
#- Song_19_Carousel
#- Song_22_Carousel