#config_version=5

player_vars:
  pf_multiplier:
    value_type: int
    initial_value: 1

  pf_Bonus_Multiplier:
    value_type: int
    initial_value: 1

  pf_setlist:
    value_type: int
    initial_value: 1

  pf_album:
    value_type: int
    initial_value: 1

  pf_drop_target_level:
    value_type: int
    initial_value: 1
