#config_version=5

playlists:
  playlistJukebox:
    sounds:
      - Apathy_track
      - Bombshell_track
      - Cult_track
      - Danger_track
      - Destroy_track
      - Voices_track
      - Free_track
      - Heroes_track
      - Hey_track
      - Human_track
      - Invade_track
      - Mega_track
      - Nobody_track
      - Organizized_track
      - Riot_track
      - Showme_track
      - Sid_track
      - Supernova_track
      - Villain_track
      - Everything_track
      - Revolution_track
      - Vampire_track
      - Worlds_track
      - Wild_track
      - Love_track
      - Hostage_track
      - Match_track
      - Walking_track
      - Return_track
      - City_track
      - Ultra_track