#config_version=5

player_vars:
  pf_multiplier:
    value_type: int
    initial_value: 1

  pf_Bonus_Multiplier:
    value_type: int
    initial_value: 1

  pf_setlist:
    value_type: int
    initial_value: 1

  pf_album:
    value_type: int
    initial_value: 1
    
  pf_Jukebox_Control:
    value_type: int
    initial_value: 0

  pf_Jukebox_Hits:
    value_type: int
    initial_value: 0