#config_version=5

sounds:
  Apathy_track:
    file: A Is For Apathy.flac
    priority: 200  
  Bombshell_track:
    file: Bombshell.flac
    priority: 200
  Cult_track:
    file: Cult Leader.flac
    priority: 200
  Danger_track:
    file: Danger Is Go.flac
    priority: 200
  Destroy_track:
    file: Destroy What You Enjoy.flac
    priority: 200
  Voices_track:
    file: Footsteps and Voices.flac
    priority: 200
  Free_track:
    file: Free.flac
    priority: 200
  Heroes_track:
    file: Heroes and Villains.flac
    priority: 200
  Hey_track:
    file: Hey All You People.flac
    priority: 200
  Human_track:
    file: How To Be a Human.flac
    priority: 200
  Invade_track:
    file: Invade, Destroy, Repeat.flac
    priority: 100
  Mega_track:
    file: Mega Kung Fu Radio.flac
    priority: 200
  Nobody_track:
    file: Nobodys Real.flac
    priority: 200
  Organizized_track:
    file: Organizized.flac
    priority: 200
  Riot_track:
    file: Riot Time.flac
    priority: 200
  Showme_track:
    file: Show Me What You've Got.flac
    priority: 200
  Sid_track:
    file: Sid Vicious in a Dress.flac
    priority: 200
  Supernova_track:
    file: Super Nova Goes Pop.flac
    priority: 200
  Villain_track:
    file: Super Villain.flac
    priority: 200
  Everything_track:
    file: The End Of Everything.flac
    priority: 200
  Revolution_track:
    file: Theme To A Fake Revolution.flac
    priority: 200
  Vampire_track:
    file: V Is For Vampire.flac
    priority: 200
  Worlds_track:
    file: When Worlds Collide.flac
    priority: 200
  Wild_track:
    file: Wild World.flac
    priority: 200
  Love_track:
    file: You're Gonna Love It, If You Like.flac
    priority: 200 
  Hostage_track:
    file: Hostage.flac
    priority: 200
  Match_track:
    file: Strike The Match.flac
    priority: 200
  Walking_track:
    file: Walking Disaster.flac
    priority: 200
  Return_track:
    file: Return To The City Of The Dead.flac
    priority: 200
  City_track:
    file: City Lights.flac
    priority: 200
  Ultra_track:
    file: Ultra Mega.flac
    priority: 200
  Instrumental_track:
    file: Heroes and Villains Instrumental.flac
    priority: 200
  Watch_track:
    file: Watch the Sky for Me.wav
    priority: 300
 
  pop_bumpers_01:
    file: pop_bumpers_01.wav
    priority: 200
  pop_bumpers_02:
    file: pop_bumpers_02.wav
    priority: 200
  pop_bumpers_03:
    file: pop_bumpers_03.wav
    priority: 200
  pop_bumpers_04:
    file: pop_bumpers_04.wav
    priority: 200
  pop_bumpers_05:
    file: pop_bumpers_05.wav
    priority: 200
  pop_bumpers_06:
    file: pop_bumpers_06.wav
    priority: 200
  pop_bumpers_07:
    file: pop_bumpers_07.wav
    priority: 200
  pop_bumpers_08:
    file: pop_bumpers_08.wav
    priority: 200
  pop_bumpers_09:
    file: pop_bumpers_09.wav
    priority: 200
  pop_bumpers_10:
    file: pop_bumpers_10.wav
    priority: 200
  pop_bumpers_11:
    file: pop_bumpers_11.wav
    priority: 200
  pop_bumpers_12:
    file: pop_bumpers_12.wav
    priority: 200
  pop_bumpers_13:
    file: pop_bumpers_13.wav
    priority: 200
  pop_bumpers_14:
    file: pop_bumpers_14.wav
    priority: 200
  pop_bumpers_15:
    file: pop_bumpers_15.wav
    priority: 200
  pop_bumpers_16:
    file: pop_bumpers_16.wav
    priority: 200
  #pop_bumpers_17:
  #  file: pop_bumpers_17.wav
  #  priority: 200
  pop_bumpers_18:
    file: pop_bumpers_18.wav
    priority: 200
  pop_bumpers_19:
    file: pop_bumpers_19.wav
    priority: 200
  super_pops:
    file: super_pops.wav
    priority: 500
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 2.0 sec
      release: 1.0 sec

  releasing_drones:
    file: releasing_drones.flac
    priority: 1000
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 2.0 sec
      release: 1.0 sec

  new_album_collected:
    file: new_album_collected.flac
    priority: 400
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 2.0 sec
      release: 1.0 sec

  target_01:
    file: target_01.wav
    priority: 200
    volume: 2
  target_02:
    file: target_02.wav
    priority: 200
    volume: 2
  target_03:
    file: target_03.wav
    priority: 200
    volume: 2  
  target_04:
    file: target_04.wav
    priority: 200
    volume: 2
  target_05:
    file: target_05.wav
    priority: 200
    volume: 2
  target_06:
    file: target_06.wav
    priority: 200
    volume: 2
  target_07:
    file: target_07.wav
    priority: 200
    volume: 2
  target_08:
    file: target_08.wav
    priority: 200
    volume: 2
  target_09:
    file: target_09.wav
    priority: 200
    volume: 2
  target_10:
    file: target_10.wav
    priority: 200
    volume: 2

  extra_ball:
    file: extra_ball.wav
    priority: 800
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 2.0 sec
      release: 1.0 sec

  intro:
    file: intro.wav
    priority: 400
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 3.0 sec
      release: 1.0 sec

  chant:
    file: powerman_chant.wav
    priority: 400
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 2.0 sec
      release: 1.0 sec

  cheering:
    file: crowd_cheering.wav
    priority: 400
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 2.0 sec
      release: 1.0 sec

  match_made:
    file: match.wav
    priority: 400
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 2.0 sec
      release: 1.0 s

  no_match:
    file: no_match.wav
    priority: 400
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 2.0 sec
      release: 1.0 s

  riff_01:
    file: riff_01.wav
    priority: 200
    volume: 2