#config_version=5

mode:
  start_events: start_mode_Member_11
  stop_events: ball_ended, mode_Member_Award_04_starting
  priority: 200

show_player:
  mode_Member_11_started: 
    BSRS_Album:
      loops: 0
      speed: 1