#config_version=5

mode:
  start_events: start_mode_Album_14
  stop_events: ball_ended, mode_Album_Award_Jackpot_starting
  priority: 200

show_player:
  mode_Album_14_started: 
    NW_Album:
      loops: 0
      speed: 1