#config_version=5

mode:
  start_events: drop_target_shot_hit
  stop_events: ball_ending, drop_target_bank_ramp_drop_target_up
  priority: 200

timers:
  drop_target_01:
    debug: True
    start_value: 10
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: mode_drop_target_ramp_entrance_started
        action: start
      - event: load_chamber_shot_hit
        action: stop