#config_version=5

mode:
  start_events: ball_started
  stop_events: ball_ending
  priority: 200

timers:
  drop_target_01:
    debug: True
    start_value: 10
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: drop_target_shot_hit
        action: start