#config_version=5

mode:
  start_events: start_mode_clip_10
  stop_events: ball_ended, mode_Spider_starting
  priority: 300

show_player:
  mode_clip_10_started: 
    play_clip_10:
      loops: 0
      speed: 1