#config_version=5

mode:
  start_events: start_mode_Song_23
  stop_events: ball_ended, mode_Red_starting
  priority: 200

sound_player:
  mode_Song_23_started:
    Apathy_track:
      action: play
      loops: -1
  ball_ending:
    Apathy_track:
      action: stop

slides:
  pick_Song23_slide: #A Is For Apathy
    widgets:
      - type: image
        image: transform
    transition:
      type: move_in
      direction: right

slide_player:
  mode_Song_23_started: 
    pick_Song23_slide:
      expire: 5s
      target: dmd