#config_version=5

mode:
  start_events: Jukebox_Start{current_player.pf_setlist==3}
  stop_events: ball_ended, mode_Song_Carousel_10_starting
  priority: 200

event_player:
  mode_Song_Carousel_7_started: play_random_song_3

random_event_player:
  play_random_song_3:
    force_different: true
    events:
      - Song_7
      - Song_8
      - Song_9

sound_player:
  mode_Song_Carousel_7_starting:
    Instrumental_track:
      action: stop
    Supernova_track:
      action: stop
    Free_track:
      action: stop
    Human_track:
      action: stop
    cheering:
      action: play
      loops: 0  

  mode_Song_Carousel_7_ending:
    Cult_track:
      action: stop
    Wild_track:
      action: stop
    Organizized_track:
      action: stop

  Song_7:
    Wild_track:
      action: play
      loops: -1

  Song_8:
    Cult_track:
      action: play
      loops: -1

  Song_9:
    Organizized_track:
      action: play
      loops: -1

variable_player:
  
  mode_Song_Carousel_7_started:
    pf_setlist:
      int: 4
      action: set
    pf_Album_3_Ready:
      int: 0
      action: set

show_player:
  Song_7: 
    wild_track:
      loops: 0
      speed: 1
  Song_8: 
    cult_track:
      loops: 0
      speed: 1
  Song_9: 
    organizized_track:
      loops: 0
      speed: 1

  mode_Song_Carousel_7_started:
    Guitar_4K_On:
      show_tokens:
        lights: Guitar_4X