#config_version=5

mode:
  start_events: start_mode_Member_04
  stop_events: ball_ended, mode_Member_Award_02_starting
  priority: 200

show_player:
  mode_Member_04_started: 
    BSRS_Album:
      loops: 0
      speed: 1