#config_version=5

mode:
  start_events: start_mode_Song_22_Carousel
  stop_events: mode_Song_22_start, mode_Song_23_start, mode_Song_24_start
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 2400

mode_settings:
  selectable_items: Song22, Song23, Song24, 
  select_item_events: sw_Both_Flippers
  next_item_events: sw_right_flipper_active
  previous_item_events: sw_left_flipper_active

queue_relay_player:
  balldevice_bd_right_saucer_eject_attempt:
    post: start_mode_Song_22_Carousel
    wait_for: mode_Song_22_start, mode_Song_23_start, mode_Song_24_start

slide_player:
  carousel_Song24_highlighted: select_Song24
  carousel_Song23_highlighted: select_Song23
  carousel_Song24_highlighted: select_Song24

slides:
  select_Song22: #Riot Time
    widgets:
      - type: image
        image: test2
    transition:
      type: move_in
      direction: right
  select_Song23: #A Is For Apathy
    widgets:
      - type: image
        image: transform
    transition:
      type: move_in
      direction: right
  select_Song24: #Return To The City Of The Dead
    widgets:
      - type: image
        image: dwye
    transition:
      type: move_in
      direction: right
 
event_player:
  select_Song224224: mode_Song_22_start
  select_Song224: mode_Song_23_start
  select_Song24: mode_Song_24_start  