#config_version=5

mode:
  start_events: ball_starting
  stop_events: carousel_Doctor1_selected, carousel_Doctor2_selected, carousel_Doctor3_selected, carousel_Doctor4_selected, carousel_Doctor5_selected, carousel_Doctor6_selected, carousel_Doctor7_selected, carousel_Doctor8_selected
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 125

mode_settings:
  selectable_items: Doctor1, Doctor2, Doctor3, Doctor4, Doctor5, Doctor6, Doctor7, Doctor8
  select_item_events: sw_launch_active
  next_item_events: sw_right_flipper_active
  previous_item_events: sw_left_flipper_active

slide_player:
  carousel_Doctor1_highlighted: select_Doctor1
  carousel_Doctor2_highlighted: select_Doctor2
  carousel_Doctor3_highlighted: select_Doctor3
  carousel_Doctor4_highlighted: select_Doctor4
  carousel_Doctor5_highlighted: select_Doctor5
  carousel_Doctor6_highlighted: select_Doctor6
  carousel_Doctor7_highlighted: select_Doctor7
  carousel_Doctor8_highlighted: select_Doctor8

slides:
  select_Doctor1:
    widgets:
      - type: text
        text: Doctor 1
        font_size: 10
        color: yellow
    transition:
      type: move_in
      direction: right
  select_Doctor2:
      widgets:
        - type: text
          text: Doctor 2
          font_size: 10
          color: yellow
      transition:
        type: move_in
        direction: right
  select_Doctor3:
      widgets:
        - type: text
          text: Doctor 3
          font_size: 10
          color: yellow
      transition:
        type: move_in
        direction: right
  select_Doctor4:
      widgets:
        - type: text
          text: Doctor 4
          font_size: 10
          color: yellow
      transition:
        type: move_in
        direction: right
  select_Doctor5:
      widgets:
        - type: text
          text: Doctor 5
          font_size: 10
          color: yellow
      transition:
        type: move_in
        direction: right
  select_Doctor6:
      widgets:
        - type: text
          text: Doctor 6
          font_size: 10
          color: yellow
      transition:
        type: move_in
        direction: right
  select_Doctor7:
      widgets:
        - type: text
          text: Doctor 7
          font_size: 10
          color: yellow
      transition:
        type: move_in
        direction: right
  select_Doctor8:
      widgets:
        - type: text
          text: Doctor 8
          font_size: 10
          color: yellow
      transition:
        type: move_in
        direction: right

event_player:
  select_Doctor1: mode_Doctor_1_start
  select_Doctor2: mode_Doctor_2_start
  select_Doctor3: mode_Doctor_3_start
  select_Doctor4: mode_Doctor_4_start
  select_Doctor5: mode_Doctor_5_start
  select_Doctor6: mode_Doctor_6_start
  select_Doctor7: mode_Doctor_7_start
  select_Doctor8: mode_Doctor_8_start