#config_version=5

mode:
  start_events: start_mode_Album_08
  stop_events: ball_ended, mode_Album_Award_04_starting
  priority: 200

show_player:
  mode_Album_08_started: 
    DWYE_Album:
      loops: 0
      speed: 1