#config_version=5

mode:
  start_events: balldevice_bd_left_saucer_ball_entered{current_player.pf_member==2}  
  stop_events: ball_ended, mode_Member_Award_03_starting
  priority: 200

event_player:
  mode_Member_Award_02_started: award_random_member_2

random_event_player:
  award_random_member_2:
    force_different: true
    events:
      - start_mode_Member_05
      - start_mode_Member_06
      - start_mode_Member_07
      - start_mode_Member_08

variable_player:
  mode_Member_Award_02_started:
    pf_member:
      int: 3
      action: set

  balldevice_bd_left_saucer_ball_entered:
    score: 1000 * current_player.pf_multiplier
