#config_version=5

mode:
  start_events: start_mode_Song_9
  stop_events: mode_Song_Carousel_10_starting
  priority: 200

sound_player:
  mode_Song_9_started:
    Organizized_track:
      action: play
      loops: -1
  ball_ending:
    Organizized_track:
      action: stop

show_player:
  mode_Song_9_started: 
    organizized_track:
      loops: 0
      speed: 1