#config_version=5

mode:
  start_events: start_mode_Song_9
  stop_events: ball_ended, mode_Song_Carousel_10_starting
  priority: 200

sound_player:
  mode_Song_9_started:
    Organizized_track:
      action: play
      loops: -1
  ball_ending:
    Organizized_track:
      action: stop

slides:
  pick_Song9_slide: #Organizized
    - type: video
      video: organizized_track
      control_events:
        - event: bd_right_saucer_ball_eject_success
          action: stop
slide_player:
  mode_Song_9_started: 
    pick_Song9_slide:
      target: dmd