#config_version=5

mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 125

counters:
  lb_PM5K_complete_count:
    count_events: PM5K_Targets_complete
    events_when_hit: PM5K_Targets_done
    count_complete_value: 5
    starting_count: 0
    direction: up
    persist_state: false
    reset_on_complete: True
    events_when_complete: PM5K_ready
    enable_events: mode_PM5K_made_started, reset_PM5K
    debug: true

shots:
  PM5K:
    switch: s_PM5K_target
    show_tokens:
      light: l_left_25K_target

shot_groups:
  PM5K_Targets:
    shots: PM5K
    reset_events: 
      PM5K_Targets_complete: 1s

variable_player:
  PM5K_Targets_done{count==1}:
    score: 100 * current_player.pf_multiplier|block
  PM5K_Targets_done{count==2}:
    score: 200 * current_player.pf_multiplier|block
  PM5K_Targets_done{count==3}:
    score: 300 * current_player.pf_multiplier|block
  PM5K_Targets_done{count==4}:
    score: 400 * current_player.pf_multiplier|block
  PM5K_Targets_done{count==5}:
    score: 1000 * current_player.pf_multiplier|block
  PM5K_Targets_done{device.sequences.lb_Next_Song.value>=1}:
    score: 50 * current_player.pf_multiplier
show_player:
  PM5K_Targets_done{count==1}:
    PM5K_P_On:
      show_tokens:
        lights: PM5K_P
  PM5K_Targets_done{count==2}:
    PM5K_M_On:
      show_tokens:
        lights: PM5K_P, PM5K_M
  PM5K_Targets_done{count==3}:
    PM5K_Skull_On:
      show_tokens:
        lights: PM5K_P, PM5K_M, PM5K_Skull
  PM5K_Targets_done{count==4}:
    PM5K_5_On:
      show_tokens:
        lights: PM5K_P, PM5K_M, PM5K_Skull, PM5K_5
  PM5K_Targets_done{count==5}:
    PM5K_K_On:
      show_tokens:
        lights: PM5K_P, PM5K_M, PM5K_Skull, PM5K_5, PM5K_K

sequences:
  lb_Next_Song:
    debug: true
    enable_events: mode_PM5K_made_started, reset_PM5K
    events:
      - PM5K_ready
      - balldevice_bd_right_saucer_ball_enter
    events_when_complete: 
      - reset_PM5K