#config_version=5

mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 125

counters:
  lb_ALBUM_complete:
    count_events: ALBUM_Targets_complete
    events_when_hit: ALBUM_Targets_done
    count_complete_value: 5
    starting_count: 0
    direction: up
    persist_state: false
    reset_on_complete: True
    events_when_complete: ALBUM_ready
    restart_events: reset_ALBUM

  lb_PM5K_complete:
    count_events: PM5K_Targets_complete
    events_when_hit: PM5K_Targets_done
    count_complete_value: 5
    starting_count: 0
    direction: up
    persist_state: false
    reset_on_complete: True
    events_when_complete: PM5K_ready
    restart_events: reset_PM5K

  lb_album_hurry_up_setup:
    count_events: reset_ALBUM
    events_when_hit: album_hurry_up_hit
    count_complete_value: 5
    starting_count: 0
    direction: up
    persist_state: false
    reset_on_complete: True
    events_when_complete: Album_Hurry_Up_Ready
    restart_events: mode_album_hurry_up_ended

shots:
  ALBUM:
    switch: s_album_target
  PM5K:
    switch: s_PM5K_target

shot_groups:
  ALBUM_Targets:
    shots: ALBUM
    reset_events: 
      ALBUM_Targets_complete: 1s
  PM5K_Targets:
    shots: PM5K
    reset_events: 
      PM5K_Targets_complete: 1s

variable_player:
  ALBUM_Targets_done{count==1}:
    score: 1000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  ALBUM_Targets_done{count==2}:
    score: 2000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  ALBUM_Targets_done{count==3}:
    score: 3000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  ALBUM_Targets_done{count==4}:
    score: 4000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  ALBUM_Targets_done{count==5}:
    score: 10000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  ALBUM_ready:
      pf_album_bonus: 1
  PM5K_Targets_done{count==1}:
    score: 1000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  PM5K_Targets_done{count==2}:
    score: 2000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  PM5K_Targets_done{count==3}:
    score: 3000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  PM5K_Targets_done{count==4}:
    score: 4000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  PM5K_Targets_done{count==5}:
    score: 10000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  PM5K_hit:
    pf_PM5K_bonus: 1
  balldevice_bd_left_saucer_ball_entered:
    score: 20000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block

show_player:
  ALBUM_Targets_done{count==1}:
    Album_A_On:
      show_tokens:
        lights: Album_a
  ALBUM_Targets_done{count==2}:
    Album_L_On:
      show_tokens:
        lights: Album_l
  ALBUM_Targets_done{count==3}:
    Album_B_On:
      show_tokens:
        lights: Album_b
  ALBUM_Targets_done{count==4}:
    Album_U_On:
      show_tokens:
        lights: Album_u
  ALBUM_Targets_done{count==5}:
    Album_M_On:
      show_tokens:
        lights: Album_m

  PM5K_Targets_done{count==1}:
    PM5K_P_On:
      show_tokens:
        lights: PM5K_P
  PM5K_Targets_done{count==2}:
    PM5K_M_On:
      show_tokens:
        lights: PM5K_M
  PM5K_Targets_done{count==3}:
    PM5K_Skull_On:
      show_tokens:
        lights: PM5K_Skull
  PM5K_Targets_done{count==4}:
    PM5K_5_On:
      show_tokens:
        lights: PM5K_5
  PM5K_Targets_done{count==5}:
    PM5K_K_On:
      show_tokens:
        lights: PM5K_K

  reset_ALBUM:
    Album_Off:
      show_tokens:
        Album_a, Album_l, Album_b, Album_u, Album_m

  reset_PM5K:
    PM5K_Off:
      show_tokens:
        PM5K_P, PM5K_M, PM5K_Skull, PM5K_5, PM5K_K


  Album_01: 
    True_Force_Album:
      loops: 0
      speed: 1
  Album_02: 
    BSRS_Album:
      loops: 0
      speed: 1
  Album_03: 
    MKFR_Album:
      loops: 0
      speed: 1
  Album_04: 
    TTSR_Album:
      loops: 0
      speed: 1
  Album_05: 
    AFD_Album:
      loops: 0
      speed: 1
  Album_06: 
    Transform_Album:
      loops: 0
      speed: 1
  Album_07: 
    DWYE_Album:
      loops: 0
      speed: 1
  Album_08: 
    TGTBTUV1_Album:
      loops: 0
      speed: 1
  Album_09: 
    SOTOSON_Album:
      loops: 0
      speed: 1
  Album_10: 
    CCR_Album:
      loops: 0
      speed: 1
  Album_11: 
    BOTF_Album:
      loops: 0
      speed: 1
  Album_12: 
    NW_Album:
      loops: 0
      speed: 1

  ALBUM_award_ready:
    flash: 
      loops: -1
      speed: 10
      show_tokens:
        lights: Next_Album

  reset_album_award:
    flash: 
      loops: 0
      speed: 4
      show_tokens:
        lights: Next_Album

accruals:
  lb_ALBUM_award:
    events:
      - ALBUM_ready
      - PM5K_ready
    events_when_complete: ALBUM_award_ready
    persist_state: false
    reset_on_complete: true
    restart_events: reset_album_award

sequences:
  lb_Next_Album:
    enable_events: mode_ALBUM_made_started, reset_ALBUM
    events:
      - ALBUM_award_ready
      - balldevice_bd_left_saucer_ball_enter
    events_when_complete: 
      - reset_ALBUM
      - reset_PM5K
      - reset_album_award

random_event_player:
  reset_album_award:
    force_different: true
    events:
      - Album_01
      - Album_02
      - Album_03
      - Album_04
      - Album_05
      - Album_06
      - Album_07
      - Album_08
      - Album_09
      - Album_10
      - Album_11
      - Album_12

sound_player:
  reset_album_award:
    new_album_collected:
      action: play
      loops: 0


timers:  
  lb_left_saucer_eject:
    start_value: 4
    end_value: 0
    direction: down
    tick_interval: 1
    control_events:
      - event: balldevice_bd_left_saucer_ball_entered
        action: start