#config_version=5

mode:
  start_events: ball_starting
  priority: 125

counters:
  lb_ALBUM_complete_count:
    count_events: ALBUM_Targets_complete
    events_when_hit: ALBUM_Targets_done
    starting_count: 0
    direction: up
    persist_state: false

shots:
  ALBUM:
    switch: s_album_target
    show_tokens:
      light: l_right_25K_target
   

shot_groups:
  ALBUM_Targets:
    shots: ALBUM
    reset_events: 
      ALBUM_Targets_complete: 1s

variable_player:
  ALBUM_Targets_done{count==1}:
    score: 100 * current_player.pf_multiplier|block
  ALBUM_Targets_done{count==2}:
    score: 200 * current_player.pf_multiplier|block
  ALBUM_Targets_done{count==3}:
    score: 300 * current_player.pf_multiplier|block
  ALBUM_Targets_done{count==4}:
    score: 400 * current_player.pf_multiplier|block
  ALBUM_Targets_done{count==5}:
    score: 1000 * current_player.pf_multiplier|block
  ALBUM_Targets_done{count>=6}:
    score: 50 * current_player.pf_multiplier|block

show_player:
  ALBUM_Targets_done{count==1}:
    Album_M_On:
      show_tokens:
        lights: Album_a
  ALBUM_Targets_done{count==2}:
    Album_E_On:
      show_tokens:
        lights: Album_a, Album_l
  ALBUM_Targets_done{count==3}:
    Album_T_On:
      show_tokens:
        lights: Album_a, Album_l, Album_b
  ALBUM_Targets_done{count==4}:
    Album_A_On:
      show_tokens:
        lights: Album_a, Album_l, Album_b, Album_u
  ALBUM_Targets_done{count==5}:
    Album_L_On:
      show_tokens:
        lights: Album_a, Album_l, Album_b, Album_u, Album_m
  ALBUM_Targets_done{count>=6}:
    flash:
      loops: -1
      speed: 10
      show_tokens:
        lights: l_album_m, l_album_e, l_album_t, l_album_a, l_album_l