#config_version=5

mode:
  start_events: ball_starting
  stop_events: game_ending
  priority: 125

counters:
  lb_ALBUM_complete_count:
    count_events: ALBUM_Targets_complete
    events_when_hit: ALBUM_Targets_done
    count_complete_value: 5
    starting_count: 0
    direction: up
    persist_state: false
    reset_on_complete: True
    events_when_complete: ALBUM_ready
    enable_events: mode_ALBUM_made_started, reset_ALBUM
    debug: true

shots:
  ALBUM:
    switch: s_album_target
    show_tokens:
      light: l_right_25K_target

shot_groups:
  ALBUM_Targets:
    shots: ALBUM
    reset_events: 
      ALBUM_Targets_complete: 1s

variable_player:
  ALBUM_Targets_done{count==1}:
    score: 100 * current_player.pf_multiplier|block
  ALBUM_Targets_done{count==2}:
    score: 200 * current_player.pf_multiplier|block
  ALBUM_Targets_done{count==3}:
    score: 300 * current_player.pf_multiplier|block
  ALBUM_Targets_done{count==4}:
    score: 400 * current_player.pf_multiplier|block
  ALBUM_Targets_done{count==5}:
    score: 1000 * current_player.pf_multiplier|block
  ALBUM_Targets_done{device.sequences.lb_Next_Album.value>=1}:
    score: 50 * current_player.pf_multiplier
show_player:
  ALBUM_Targets_done{count==1}:
    Album_A_On:
      show_tokens:
        lights: Album_a
  ALBUM_Targets_done{count==2}:
    Album_L_On:
      show_tokens:
        lights: Album_a, Album_l
  ALBUM_Targets_done{count==3}:
    Album_B_On:
      show_tokens:
        lights: Album_a, Album_l, Album_b
  ALBUM_Targets_done{count==4}:
    Album_U_On:
      show_tokens:
        lights: Album_a, Album_l, Album_b, Album_u
  ALBUM_Targets_done{count==5}:
    Album_M_On:
      show_tokens:
        lights: Album_a, Album_l, Album_b, Album_u, Album_m

sequences:
  lb_Next_Album:
    debug: true
    enable_events: mode_ALBUM_made_started, reset_ALBUM
    events:
      - ALBUM_ready
      - balldevice_bd_left_saucer_ball_enter
    events_when_complete: 
      - reset_ALBUM


#True Force
#Blood Splat Rating System
#Mega! Kung Fu Radio
#Tonight The Stars Revolt
#Backstage and Beyond the Infinite
#Anyone For Doomsday?
#Transform
#The Good, The Bad, and the Ugly, Vol 1
#Destroy What You Enjoy
#Copies Clones and Replicants
#The Korea EP
#Somewhere on the other side of nowhere
#Builders of the Future
#New Wave