#config_version=5

queue_relay_player:
  match_no_match:
    post: no_match
    wait_for: slide_no_match_slide_removed
    pass_args: True
  match_has_match:
    post: has_match
    wait_for: slide_match_slide_removed
    pass_args: True

mode_settings:
  non_match_number_step: 10

slide_player:
  no_match:
    no_match_slide:
      expire: 3s
  has_match:
    match_slide:
      expire: 3s

sound_player:
  no_match:
    no_match:
      action: play
  has_match:
    match_made:
      action: play
  mode_match_started:
    Instrumental_track:
      action: stop
    Watch_track:
      action: play
      loops: 0

slides:
  match_slide:
    - type: text
      text: MATCH
      font_size: 14
      anchor_y: center
      x: 50
    - type: text
      font_size: 10
      anchor_x: left
      anchor_y: bottom
      x: 2
      y: 25
      text: "(match_number0)"
    - type: text
      font_size: 10
      anchor_x: right
      anchor_y: bottom
      x: 127
      y: 25
      text: "(match_number1)"
    - type: text
      font_size: 10
      anchor_x: left
      anchor_y: bottom
      x: 2
      y: 2
      text: "(match_number2)"
    - type: text
      font_size: 10
      anchor_x: right
      anchor_y: bottom
      x: 127
      y: 2
      text: "(match_number3)"
    - type: text
      font_size: 14
      anchor_x: center
      anchor_y: center
      x: 80
      text: "(winner_number)"
  no_match_slide:
    - type: text
      text: NO MATCH
      font_size: 14
      anchor_y: center
      x: 50
    - type: text
      font_size: 10
      anchor_x: left
      anchor_y: bottom
      x: 2
      y: 25
      text: "(match_number0)"
    - type: text
      font_size: 10
      anchor_x: right
      anchor_y: bottom
      x: 127
      y: 25
      text: "(match_number1)"
    - type: text
      font_size: 10
      anchor_x: left
      anchor_y: bottom
      x: 2
      y: 2
      text: "(match_number2)"
    - type: text
      font_size: 10
      anchor_x: right
      anchor_y: bottom
      x: 127
      y: 2
      text: "(match_number3)"
    - type: text
      font_size: 14
      anchor_x: center
      anchor_y: center
      x: 90
      text: "(winner_number)"