#config_version=5

mode:
  start_events: balldevice_bd_left_saucer_ball_entered{current_player.pf_album==5}  
  stop_events: ball_ended, mode_Album_Award_Jackpot_starting
  priority: 200

event_player:
  mode_Album_Award_05_started: award_random_album_5

random_event_player:
  award_random_album_5:
    force_different: true
    events:
      - start_mode_album_13
      - start_mode_album_14

variable_player:
  mode_Album_Award_05_started:
    pf_album:
      int: 6
      action: set

  balldevice_bd_left_saucer_ball_entered:
    score: 5000 * current_player.pf_multiplier


#Builders of the Future
#New Wave