#config_version=5

mode:
  start_events: start_mode_Song_20
  stop_events: mode_Song_Carousel_22_starting
  priority: 200

sound_player:
  mode_Song_20_started:
    Nobody_track:
      action: play
      loops: -1
  ball_ending:
    Nobody_track:
      action: stop

show_player:
  mode_Song_20_started: 
    nobodys_track:
      loops: 0
      speed: 1