#config_version=5

mode:
  start_events: start_mode_Song_20
  stop_events: ball_ended, mode_Song_Carousel_22_starting
  priority: 200

sound_player:
  mode_Song_20_started:
    Nobody_track:
      action: play
      loops: -1
  ball_ending:
    Nobody_track:
      action: stop

slides:
  pick_Song20_slide: #Nobody's Real
    widgets:
      - type: image
        image: ttsr
    transition:
      type: move_in
      direction: right

slide_player:
  mode_Song_20_started: 
    pick_Song20_slide:
      expire: 5s
      target: dmd