#config_version=5

mode:
  start_events: start_mode_Song_15_Carousel
  stop_events: mode_Song_115_start, mode_Song_14_start, mode_Song_15_start
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 300

mode_settings:
  selectable_items: Song15, Song14, Song15, 
  select_item_events: sw_Both_Flippers
  next_item_events: sw_right_flipper_active
  previous_item_events: sw_left_flipper_active

queue_relay_player:
  balldevice_bd_right_saucer_eject_attempt:
    post: start_mode_Song_15_Carousel
    wait_for: mode_Song_15_start, mode_Song_14_start, mode_Song_15_start

slide_player:
  carousel_Song115_highlighted: select_Song15
  carousel_Song14_highlighted: select_Song14
  carousel_Song15_highlighted: select_Song15

slides:
  select_Song115: #Sid Vicious In A Dress
    widgets:
      - type: image
        image: nw
    transition:
      type: move_in
      direction: right
  select_Song14: #Super Villain
    widgets:
      - type: image
        image: sotoson
    transition:
      type: move_in
      direction: right
  select_Song15: #Hey All You People
    widgets:
      - type: image
        image: bof
    transition:
      type: move_in
      direction: right
 
event_player:
  select_Song115: mode_Song_15_start
  select_Song14: mode_Song_14_start
  select_Song15: mode_Song_15_start  