#config_version=5

mode:
  start_events: start_mode_clip_25
  stop_events: ball_ended, mode_Spider_starting
  priority: 200

show_player:
  mode_clip_25_started: 
    play_clip_25:
      loops: 0
      speed: .5