#config_version=5

mode:
  start_events: start_mode_Song_12
  stop_events: ball_ended, mode_Song_Carousel_13_starting
  priority: 200

sound_player:
  mode_Song_12_started:
    Danger_track:
      action: play
      loops: -1
  ball_ending:
    Danger_track:
      action: stop

show_player:
  mode_Song_12_started: 
    danger_track:
      loops: 0
      speed: 1