#config_version=5

mode:
  start_events: Jukebox_Start{current_player.pf_setlist==5}
  stop_events: ball_ended, mode_Song_Carousel_16_starting
  priority: 200

event_player:
  mode_Song_Carousel_13_started: play_random_song_5

random_event_player:
  play_random_song_5:
    force_different: true
    events:
      - Song_13
      - Song_14
      - Song_15

sound_player:
  mode_Song_Carousel_13_starting:
    Instrumental_track:
      action: stop
    Destroy_track:
      action: stop
    Vampire_track:
      action: stop
    Danger_track:
      action: stop
 
  mode_Song_Carousel_13_ending:
    Hey_track:
      action: stop
    Villain_track:
      action: stop
    Sid_track:
      action: stop

  Song_13:
    Hey_track:
      action: play
      loops: -1

  Song_14:
    Villain_track:
      action: play
      loops: -1

  Song_15:
    Sid_track:
      action: play
      loops: -1

variable_player:
  mode_Song_Carousel_13_started:
    pf_setlist:
      int: 6
      action: set
    pf_Album_5_Ready:
      int: 0
      action: set

show_player:
  Song_13: 
    hey_track:
      loops: 0
      speed: 1

  Song_14: 
    villain_track:
      loops: 0
      speed: 1

  Song_15: 
    sid_track:
      loops: 0
      speed: 1


  mode_Song_Carousel_13_started:
    Guitar_16K_On:
      show_tokens:
        lights: Guitar_16X