#config_version=5

mode:
  start_events: reset_ALBUM 
  stop_events: 
    - ball_ended
    - start_mode_Album_01
    - start_mode_Album_02
    - start_mode_Album_03
    - start_mode_Album_04
    - start_mode_Album_05
    - start_mode_Album_06
    - start_mode_Album_07
    - start_mode_Album_08
    - start_mode_Album_09
    - start_mode_Album_10
    - start_mode_Album_11
    - start_mode_Album_12
  priority: 300

event_player:
  mode_Album_Award_01_started: award_random_album

random_event_player:
  award_random_album:
    force_different: true
    events:
      - start_mode_Album_01
      - start_mode_Album_02
      - start_mode_Album_03
      - start_mode_Album_04
      - start_mode_Album_05
      - start_mode_Album_06
      - start_mode_Album_07
      - start_mode_Album_08
      - start_mode_Album_09
      - start_mode_Album_10
      - start_mode_Album_11
      - start_mode_Album_12

variable_player:
  balldevice_bd_left_saucer_ball_entered:
    score: 20000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block

show_player:
  mode_Album_Award_01_started:
    PM5K_Off:
      show_tokens:
        lights: PM5K_P, PM5K_M, PM5K_Skull, PM5K_5, PM5K_K
    Album_Off:
      show_tokens:
        lights: Album_a, Album_l, Album_b, Album_u, Album_m

sound_player:
  award_random_album:
    new_album_collected:
      action: play
      loops: 0