#config_version=5

mode:
  start_events: reset_ALBUM{current_player.pf_album==1}  
  stop_events: ball_ended, mode_Album_Award_02_starting
  priority: 200

event_player:
  mode_Album_Award_01_started: award_random_album_1

random_event_player:
  award_random_album_1:
    force_different: true
    events:
      - start_mode_Album_01
      - start_mode_Album_02
      - start_mode_Album_03

variable_player:
  mode_Album_Award_01_started:
    pf_album:
      int: 2
      action: set

  balldevice_bd_left_saucer_ball_entered:
    score: 10000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block

show_player:
  mode_Album_Award_01_started:
    Album_Off:
      show_tokens:
        lights: l_album_a, l_album_l, l_album_b, l_albumu, l_album_m
        
sound_player:
  award_random_album_1:
    new_album_collected:
      action: play
      loops: 0