#config_version=5

mode:
  start_events: reset_ALBUM 
  stop_events: balldevice_bd_left_saucer_ball_eject_success

  priority: 300

event_player:
  mode_Album_Award_01_started: award_random_album

random_event_player:
  award_random_album:
    force_different: true
    events:
      - Album_01
      - Album_02
      - Album_03
      - Album_04
      - Album_05
      - Album_06
      - Album_07
      - Album_08
      - Album_09
      - Album_10
      - Album_11
      - Album_12

variable_player:
  balldevice_bd_left_saucer_ball_entered:
    score: 20000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block

show_player:
  mode_Album_Award_01_started:
    PM5K_Off:
      show_tokens:
        lights: PM5K_P, PM5K_M, PM5K_Skull, PM5K_5, PM5K_K
    Album_Off:
      show_tokens:
        lights: Album_a, Album_l, Album_b, Album_u, Album_m

  Album_01: 
    True_Force_Album:
      loops: 0
      speed: 1
  Album_02: 
    BSRS_Album:
      loops: 0
      speed: 1
  Album_03: 
    MKFR_Album:
      loops: 0
      speed: 1
  Album_04: 
    TTSR_Album:
      loops: 0
      speed: 1
  Album_05: 
    AFD_Album:
      loops: 0
      speed: 1
  Album_06: 
    Transform_Album:
      loops: 0
      speed: 1
  Album_07: 
    DWYE_Album:
      loops: 0
      speed: 1
  Album_08: 
    TGTBTUV1_Album:
      loops: 0
      speed: 1
  Album_09: 
    SOTOSON_Album:
      loops: 0
      speed: 1
  Album_10: 
    CCR_Album:
      loops: 0
      speed: 1
  Album_11: 
    BOTF_Album:
      loops: 0
      speed: 1
  Album_12: 
    NW_Album:
      loops: 0
      speed: 1

sound_player:
  award_random_album:
    new_album_collected:
      action: play
      loops: 0