#config_version=5

mode:
  start_events: balldevice_bd_left_saucer_ball_entered{current_player.pf_member==4}  
  stop_events: ball_ended, mode_Member_Award_05_starting
  priority: 200

event_player:
  mode_Member_Award_04_started: award_random_member_4

random_event_player:
  award_random_member_4:
    force_different: true
    events:
      - start_mode_Member_13
      - start_mode_Member_14
      - start_mode_Member_15
      - start_mode_Member_16

variable_player:
  mode_Member_Award_04_started:
    pf_member:
      int: 5
      action: set

  balldevice_bd_left_saucer_ball_entered:
    score: 1000 * current_player.pf_multiplier
