#config_version=5

mode:
  start_events: start_mode_Song_7
  stop_events: mode_Song_Carousel_10_starting
  priority: 200

sound_player:
  mode_Song_7_started:
    Wild_track:
      action: play
      loops: -1
  ball_ending:
    Wild_track:
      action: stop

show_player:
  mode_Song_7_started: 
    wild_track:
      loops: 0
      speed: 1