#config_version=5

mode:
  start_events: start_mode_Song_7
  stop_events: ball_ended, mode_Song_Carousel_10_starting
  priority: 200

sound_player:
  mode_Song_7_started:
    Wild_track:
      action: play
      loops: -1
  ball_ending:
    Wild_track:
      action: stop

slides:
  pick_Song7_slide: #Wild World
    - type: video
      video: wild_track
      control_events:
        - event: bd_right_saucer_ball_eject_success
          action: stop
slide_player:
  mode_Song_7_started: 
    pick_Song7_slide:
      target: dmd