#config_version=5

mode:
  start_events: ball_starting
  stop_events: ball_ended
  priority: 500

shots:
  right_rollover_shot:
    switch: s_right_rollover
    show_tokens:
      light: l_right_rollover
    #profile: l_cycle_profile 

  left_rollover_shot:
    switch: s_left_rollover
    show_tokens:
      light: l_left_rollover
    #profile: l_cycle_profile

timers:
  r_rollover:
    debug: True
    start_value: 10
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: left_rollover_shot_hit
        action: start
      - event: right_rollover_shot_hit
        action: restart

  l_rollover:
    start_value: 10
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: right_rollover_shot_hit
        action: start
      - event: left_return_shot_hit
        action: restart

  lb_spider_hurry_up:
    start_value: 30
    end_value: 0
    direction: down
    tick_interval: .25s
    control_events:
      - event:  Hurry_Up_Ready
        action: start
      - event: spider_shot_hit
        action: reset
      - event: mode_Spider_stopped
        action: pause
      - event: timer_lb_spider_hurry_up_stopped
        action: reset

accruals:
  lb_rollover_combo_setup:
    enable_events: left_rollover_shot_hit, right_rollover_shot_hit
    events:
      - left_rollover_shot_hit
      - right_rollover_shot_hit
    events_when_complete: Rollover_Combo_Made
    reset_on_complete: True
    persist_state: false

counters:
  lb_Hurry_Up_Setup:
    debug: True
    count_events: Rollover_Combo_Made
    starting_count: 0
    count_complete_value: 2
    count_interval: 1
    direction: up
    persist_state: false
    events_when_complete: Hurry_Up_Ready
    reset_on_complete: True
    disable_on_complete: false

variable_player:
  left_return_shot_hit:
    score: 10000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  left_25K_shot_hit:
    score: 25000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  left_rollover_shot_hit:
    score: 50000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  right_return_shot_hit:
    score: 10000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  right_25K_shot_hit:
    score: 25000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  right_rollover_shot_hit:
    score: 50000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block

  timer_lb_spider_hurry_up_started:
    temp_hurryup_value:
      action: set
      int: 120000
  spider_shot_hit:
    score: current_player.temp_hurryup_value * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
    temp_hurryup_value:
     action: add
     int: 120000
  timer_lb_spider_hurry_up_tick{current_player.temp_hurryup_value > 0}:
    temp_hurryup_value: -2500 
  timer_lb_spider_hurry_up_stopped:
    temp_hurryup_value:
      int: 0
      action: set

#event_player:
#  spider_shot_hit: start_mode_clip_10

slide_player:
  timer_lb_spider_hurry_up_started: hurry_up_slide
  spider_shot_hit:
    hurry_up_slide:
      action: remove
  timer_lb_spider_hurry_up_stopped:
    hurry_up_slide:
      action: remove

slides:
  hurry_up_slide:
    widgets:
      - type: text
        text: (temp_hurryup_value)
        number_grouping: true
        min_digits: 2
        font_size: 20
        y: 18
      - type: text
        text: PLAYER (number)
        y: 0
        x: 10
        font_size: 10
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 0
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 10
      - type: video
        video: radar
        volume: 0
        auto_play: true
        end_behavior: loop

sound_player:
  timer_lb_spider_hurry_up_started:
    hurry_up:
      action: play
      loops: 2

  spider_shot_hit:
    hurry_up:
      action: stop

  timer_lb_spider_hurry_up_stopped:
    hurry_up:
      action: stop