#config_version=5

mode:
  start_events: ball_starting
  stop_events: ball_ended
  priority: 500

shots:
  right_rollover_shot:
    switch: s_right_rollover
    show_tokens:
      light: l_right_rollover
    #profile: l_cycle_profile 

  left_rollover_shot:
    switch: s_left_rollover
    show_tokens:
      light: l_left_rollover
    #profile: l_cycle_profile

timers:
  r_rollover:
    debug: True
    start_value: 10
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: left_rollover_shot_hit
        action: start
      - event: right_rollover_shot_hit
        action: restart

  l_rollover:
    start_value: 10
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: right_rollover_shot_hit
        action: start
      - event: left_return_shot_hit
        action: restart

accruals:
  lb_rollover_combo_setup:
    enable_events: left_rollover_shot_hit, right_rollover_shot_hit
    events:
      - left_rollover_shot_hit
      - right_rollover_shot_hit
    events_when_complete: Rollover_Combo_Made
    reset_on_complete: True
    persist_state: false

counters:
  lb_Hurry_Up_Setup:
    debug: True
    count_events: Rollover_Combo_Made
    starting_count: 0
    count_complete_value: 2
    count_interval: 1
    direction: up
    persist_state: false
    events_when_complete: Hurry_Up_Ready
    reset_on_complete: True
    disable_on_complete: false

variable_player:
  left_return_shot_hit:
    score: 10000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  left_25K_shot_hit:
    score: 25000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  left_rollover_shot_hit:
    score: 50000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  right_return_shot_hit:
    score: 10000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  right_25K_shot_hit:
    score: 25000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
  right_rollover_shot_hit:
    score: 50000 * current_player.pf_multiplier * current_player.pf_MBall_multiplier|block
