#config_version=5

mode:
  start_events: start_mode_Song_11
  stop_events: mode_Song_Carousel_13_starting
  priority: 200

sound_player:
  mode_Song_11_started:
    Destroy_track:
      action: play
      loops: -1
  ball_ending:
    Destroy_track:
      action: stop

show_player:
  mode_Song_11_started: 
    destroy_track:
      loops: 0
      speed: 1