#config_version=5

mode:
  start_events: start_mode_Song_13
  stop_events: ball_ended, mode_Song_Carousel_16_starting
  priority: 200

sound_player:
  mode_Song_13_started:
    Hey_track:
      action: play
      loops: -1
  ball_ending:
    Hey_track:
      action: stop

show_player:
  mode_Song_13_started: 
    hey_track:
      loops: 0
      speed: 1