#config_version=5

mode:
  start_events: start_mode_Song_24
  stop_events: ball_ended, mode_Red_starting
  priority: 200

sound_player:
  mode_Song_24_started:
    Return_track:
      action: play
      loops: -1
  ball_ending:
    Return_track:
      action: stop

show_player:
  mode_Song_24_started: 
    return_track:
      loops: 0
      speed: 1