#config_version=5

mode:
  start_events: start_mode_Song_24
  stop_events: ball_ended, mode_Red_starting
  priority: 200

sound_player:
  mode_Song_24_started:
    Return_track:
      action: play
      loops: -1
  ball_ending:
    Return_track:
      action: stop

slides:
  pick_Song24_slide: #Return to the city of the Dead
    widgets:
      - type: image
        image: dwye
    transition:
      type: move_in
      direction: right

slide_player:
  mode_Song_24_started: 
    pick_Song24_slide:
      expire: 5s
      target: dmd